"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

from django.core.exceptions import ImproperlyConfigured


def env_bool(name, default=False):
    value = os.getenv(name, str(default)).strip().lower()
    if value not in {"1", "true", "yes", "0", "false", "no"}:
        raise ImproperlyConfigured(f"{name} must be a boolean")
    return value in {"1", "true", "yes"}


def env_list(name, default=""):
    return [value.strip() for value in os.getenv(name, default).split(",") if value.strip()]


DEBUG = env_bool("DEBUG")
DEVELOPMENT_SECRET = "dev-only-change-this-secret-key-32"
SECRET_KEY = os.getenv("SECRET_KEY", DEVELOPMENT_SECRET if DEBUG else "")
if not DEBUG and (len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5
                  or SECRET_KEY == DEVELOPMENT_SECRET or SECRET_KEY.startswith("django-insecure-")
                  or "replace-me" in SECRET_KEY.lower()):
    raise ImproperlyConfigured("Production requires a unique SECRET_KEY of at least 50 characters")

CODESPACE_NAME = os.getenv("CODESPACE_NAME", "") if DEBUG else ""
CODESPACES_DOMAIN = os.getenv("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN", "app.github.dev")
CODESPACE_BACKEND_HOST = f"{CODESPACE_NAME}-8000.{CODESPACES_DOMAIN}" if CODESPACE_NAME else ""
CODESPACE_FRONTEND_ORIGIN = f"https://{CODESPACE_NAME}-5173.{CODESPACES_DOMAIN}" if CODESPACE_NAME else ""
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ",".join(filter(None, ["localhost", "127.0.0.1", CODESPACE_BACKEND_HOST])) if DEBUG else "baharnaj.ir,www.baharnaj.ir")
PUBLIC_BACKEND_URL = os.getenv("PUBLIC_BACKEND_URL", f"https://{CODESPACE_BACKEND_HOST}" if CODESPACE_BACKEND_HOST else ("" if DEBUG else "https://baharnaj.ir")).rstrip("/")
SITE_URL = os.getenv("SITE_URL", "https://baharnaj.ir").rstrip("/")
if not DEBUG:
    if not ALLOWED_HOSTS or not set(ALLOWED_HOSTS) <= {"baharnaj.ir", "www.baharnaj.ir"}:
        raise ImproperlyConfigured("Production ALLOWED_HOSTS must contain only Baharnaj hosts")
    if any(url not in {"https://baharnaj.ir", "https://www.baharnaj.ir"} for url in [SITE_URL, PUBLIC_BACKEND_URL]):
        raise ImproperlyConfigured("Production public URLs must be Baharnaj HTTPS origins")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0" if DEBUG else "300"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD")
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "salon",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("SQLITE_PATH", BASE_DIR / "db.sqlite3"),
    }
}
if os.getenv("POSTGRES_HOST"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "baharnaj"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "fa-ir"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = Path(os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles"))
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

email_backend = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend")
email_host = os.getenv("EMAIL_HOST", "")
email_port = int(os.getenv("EMAIL_PORT", "587"))
email_host_user = os.getenv("EMAIL_HOST_USER", "")
email_host_password = os.getenv("EMAIL_HOST_PASSWORD", "")
email_use_tls = env_bool("EMAIL_USE_TLS", True)
email_use_ssl = env_bool("EMAIL_USE_SSL")
email_timeout = 15
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@baharnaj.ir")
if email_use_tls and email_use_ssl:
    raise ImproperlyConfigured("Select only one of email_use_tls and email_use_ssl")
if not DEBUG and (email_backend != "django.core.mail.backends.smtp.EmailBackend" or not email_host):
    raise ImproperlyConfigured("Production requires SMTP email_backend and email_host; configure email before deployment")
# Django 6.1 forbids mixing MAILERS with legacy EMAIL_* settings.
# Environment names remain conventional; only MAILERS is exported to Django.
MAILERS = {"default": {"BACKEND": email_backend, "OPTIONS": {
    "host": email_host, "port": email_port, "username": email_host_user,
    "password": email_host_password, "use_tls": email_use_tls,
    "use_ssl": email_use_ssl, "timeout": email_timeout,
}}}
FIREBASE_PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID", "")
FIREBASE_SERVICE_ACCOUNT_JSON = os.getenv("FIREBASE_SERVICE_ACCOUNT_JSON", "")
# Local credentials stay outside frontend builds; production can override this path.
_local_firebase_credentials = BASE_DIR / "baharnaj-firebase-adminsdk.json"
FIREBASE_SERVICE_ACCOUNT_FILE = os.getenv("FIREBASE_SERVICE_ACCOUNT_FILE", "") or (str(_local_firebase_credentials) if _local_firebase_credentials.is_file() else "")
if FIREBASE_SERVICE_ACCOUNT_FILE and not Path(FIREBASE_SERVICE_ACCOUNT_FILE).is_absolute():
    FIREBASE_SERVICE_ACCOUNT_FILE = str(BASE_DIR / FIREBASE_SERVICE_ACCOUNT_FILE)
FIREBASE_SERVICE_ACCOUNT_CONFIGURED = bool(FIREBASE_SERVICE_ACCOUNT_JSON or FIREBASE_SERVICE_ACCOUNT_FILE or FIREBASE_PROJECT_ID)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": ("rest_framework.throttling.ScopedRateThrottle",),
    "DEFAULT_THROTTLE_RATES": {"login": "5/minute", "guest_booking": "10/hour"},
}
configured_origins = env_list("CORS_ALLOWED_ORIGINS")
configured_csrf = env_list("CSRF_TRUSTED_ORIGINS")
if DEBUG:
    CORS_ALLOWED_ORIGINS = configured_origins + [
        "http://localhost:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:5174",
    ]
    CORS_ALLOWED_ORIGIN_REGEXES = [r"^https://.*-5173\.app\.github\.dev$"]
    CSRF_TRUSTED_ORIGINS = configured_csrf + [
        "http://localhost:8000",
        "https://localhost:8000",
        "http://127.0.0.1:8000",
        "https://127.0.0.1:8000",
        "https://*.app.github.dev",
    ]
else:
    CORS_ALLOWED_ORIGINS = configured_origins
    CSRF_TRUSTED_ORIGINS = configured_csrf
    if not set(configured_origins + configured_csrf) <= {"https://baharnaj.ir", "https://www.baharnaj.ir"}:
        raise ImproperlyConfigured("Production CORS/CSRF origins must be Baharnaj HTTPS origins")
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_SAMESITE = "Lax"
REFRESH_COOKIE_SECURE = env_bool("REFRESH_COOKIE_SECURE", not DEBUG)
REFRESH_COOKIE_SAMESITE = "Lax"
REFRESH_COOKIE_NAME = "baharnaj_refresh"
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}
AUTH_USER_MODEL = "salon.User"

# Telegram remains inert until explicitly configured and enabled.
INSTALLED_APPS += ['telegram_crm']
TELEGRAM_ENABLED = os.getenv('TELEGRAM_ENABLED', 'false').lower() == 'true'
TELEGRAM_DRY_RUN = os.getenv('TELEGRAM_DRY_RUN', 'true').lower() == 'true'
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME', '')
TELEGRAM_INTEGRATION_SECRET = os.getenv('TELEGRAM_INTEGRATION_SECRET', '')
TELEGRAM_BATCH_SIZE = int(os.getenv('TELEGRAM_BATCH_SIZE', '20'))
TELEGRAM_MAX_PER_MINUTE = int(os.getenv('TELEGRAM_MAX_PER_MINUTE', '20'))
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['telegram_link'] = '20/minute'

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = [*default_headers, 'x-booking-receipt']

TELEGRAM_FORCE_DISABLED = os.getenv("TELEGRAM_FORCE_DISABLED", "false").lower() in {"1", "true", "yes"}
