# Generated by Django 6.1 on 2026-09-14 09:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salon", "0025_flexible_service_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incoming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_id", models.CharField(max_length=100, unique=True)),
                ("body_digest", models.CharField(max_length=64)),
                ("response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("filters", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("text", models.TextField(max_length=3500)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="BenefitRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("fixed", models.PositiveIntegerField(default=0)),
                ("maximum", models.PositiveIntegerField(default=0)),
                ("points_cost", models.PositiveIntegerField(default=0)),
                ("services", models.ManyToManyField(to="salon.service")),
            ],
        ),
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("key", models.CharField(max_length=160, unique=True)),
                ("terms", models.JSONField()),
                ("redeemed_at", models.DateTimeField(null=True)),
                ("discount", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reserved_for",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="telegram_crm.benefitrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("text", models.TextField(max_length=3500)),
                ("filters", models.JSONField(default=dict)),
                ("terms", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="telegram_crm.benefitrule",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("reminder_hours", models.JSONField(default=list)),
                ("marketing_start", models.PositiveSmallIntegerField(default=10)),
                ("marketing_end", models.PositiveSmallIntegerField(default=20)),
                ("cap_days", models.PositiveSmallIntegerField(default=7)),
                ("birthday_enabled", models.BooleanField(default=False)),
                (
                    "points_per_toman",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="One point per this many paid toman; zero disables earning",
                    ),
                ),
                ("points_expiry_days", models.PositiveIntegerField(default=365)),
                ("reactivation_days", models.PositiveIntegerField(default=90)),
                ("reactivation_enabled", models.BooleanField(default=False)),
                ("attribution_days", models.PositiveIntegerField(default=7)),
                ("manager_daily", models.BooleanField(default=False)),
                ("manager_cancellations", models.BooleanField(default=False)),
                ("manager_failures", models.BooleanField(default=False)),
                ("hours", models.CharField(blank=True, max_length=200)),
                ("instagram_url", models.URLField(blank=True)),
                ("map_url", models.URLField(blank=True)),
                ("support_url", models.URLField(blank=True)),
                ("heartbeat", models.DateTimeField(blank=True, null=True)),
                ("worker_lease", models.DateTimeField(blank=True, null=True)),
                (
                    "birthday_gift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="telegram_crm.benefitrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=80, unique=True)),
                ("telegram_user_id", models.BigIntegerField(blank=True, null=True)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("connected", models.BooleanField(default=False)),
                ("reachable", models.BooleanField(default=True)),
                ("appointments", models.BooleanField(default=False)),
                ("marketing", models.BooleanField(default=False)),
                ("birthday", models.BooleanField(default=False)),
                ("loyalty", models.BooleanField(default=False)),
                ("care", models.BooleanField(default=False)),
                ("manager_reports", models.BooleanField(default=False)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                (
                    "birth_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("birth_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("birth_calendar", models.CharField(default="jalali", max_length=12)),
                ("suppressed_until", models.DateTimeField(blank=True, null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("changes", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="telegram_crm.connection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=240, unique=True)),
                ("generation", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=24)),
                ("text", models.TextField()),
                ("template_version", models.PositiveIntegerField(default=1)),
                ("appointment_version", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=16),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("claimed_at", models.DateTimeField(null=True)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("message_id", models.BigIntegerField(null=True)),
                ("error", models.CharField(blank=True, max_length=120)),
                ("acknowledged_at", models.DateTimeField(null=True)),
                ("tracking", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.appointment",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="telegram_crm.campaign",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="telegram_crm.connection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.appointment",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="telegram_crm.delivery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(null=True)),
                ("declined", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.appointment",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="telegram_crm.connection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_crm.connection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                ("key", models.CharField(max_length=200, unique=True)),
                ("reason", models.CharField(max_length=160)),
                ("expires_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("aftercare", models.TextField(blank=True, max_length=2000)),
                ("feedback", models.BooleanField(default=False)),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="salon.service"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["status", "scheduled_at"], name="telegram_cr_status_862204_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=("connection", "appointment"), name="one_private_feedback"
            ),
        ),
    ]
