# Generated by Django 6.1 on 2026-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_crm", "0001_initial"),
        ("salon", "0027_appointmentitem_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="status_events",
            field=models.JSONField(default=list),
        ),
    ]
