# Generated by Django 6.1 on 2026-09-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0027_appointmentitem_discount_amount_and_more"),
        ("telegram_crm", "0002_config_status_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon.appointment",
                    ),
                ),
            ],
        ),
    ]
