# Generated by Django 6.1 on 2026-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_crm", "0003_appointmentrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="first_visited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
