# Generated by Django 6.1 on 2026-09-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_crm", "0004_delivery_first_visited_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("token_ciphertext", models.TextField(blank=True)),
                ("secret_ciphertext", models.TextField(blank=True)),
                ("bot_username", models.CharField(blank=True, max_length=64)),
                ("site_url", models.URLField(blank=True)),
                ("backend_url", models.URLField(blank=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("off", "Off"), ("test", "Dry run"), ("live", "Live")],
                        default="off",
                        max_length=12,
                    ),
                ),
                ("bot_id", models.BigIntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
