# Generated by Django 6.1 on 2026-09-23 15:51

import django.db.models.deletion
import django.utils.timezone
import sms_crm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salon", "0034_user_totp_and_admin_recovery_codes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("off", "off"), ("test", "test"), ("live", "live")],
                        default="off",
                        max_length=8,
                    ),
                ),
                ("reminder_hours", models.JSONField(default=list)),
                ("enabled_events", models.JSONField(default=list)),
                ("daily_limit", models.PositiveIntegerField(default=100)),
                ("promotional_start", models.PositiveSmallIntegerField(default=9)),
                ("promotional_end", models.PositiveSmallIntegerField(default=21)),
                ("heartbeat", models.DateTimeField(blank=True, null=True)),
                ("worker_lease", models.DateTimeField(blank=True, null=True)),
                (
                    "last_provider_verification",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("provider_display", models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="SmsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking_received", "booking_received"),
                            ("booking_confirmed", "booking_confirmed"),
                            ("booking_rescheduled", "booking_rescheduled"),
                            ("booking_cancelled", "booking_cancelled"),
                            ("appointment_reminder", "appointment_reminder"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[sms_crm.models.validate_template_text]
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SmsConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("changes", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sms_consent_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmsPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointments", models.BooleanField(default=True)),
                ("marketing", models.BooleanField(default=False)),
                ("birthday", models.BooleanField(default=False)),
                ("loyalty", models.BooleanField(default=False)),
                ("care", models.BooleanField(default=False)),
                ("suppressed_until", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="booking", max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sms_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmsDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200, unique=True)),
                ("recipient", models.CharField(max_length=16)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking_received", "booking_received"),
                            ("booking_confirmed", "booking_confirmed"),
                            ("booking_rescheduled", "booking_rescheduled"),
                            ("booking_cancelled", "booking_cancelled"),
                            ("appointment_reminder", "appointment_reminder"),
                            ("test", "test"),
                        ],
                        max_length=32,
                    ),
                ),
                ("text", models.TextField()),
                ("template_version", models.PositiveIntegerField(default=1)),
                ("body_id", models.CharField(blank=True, max_length=64)),
                ("schedule_version", models.CharField(blank=True, max_length=64)),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("claimed", "claimed"),
                            ("simulated", "simulated"),
                            ("accepted", "accepted"),
                            ("delivered", "delivered"),
                            ("failed", "failed"),
                            ("unknown", "unknown"),
                            ("cancelled", "cancelled"),
                            ("expired", "expired"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("provider_id", models.CharField(blank=True, max_length=80)),
                ("provider_code", models.CharField(blank=True, max_length=40)),
                ("error", models.CharField(blank=True, max_length=80)),
                ("parts", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sms_deliveries",
                        to="salon.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "scheduled_at"], name="sms_due_idx"),
                    models.Index(fields=["status", "accepted_at"], name="sms_poll_idx"),
                    models.Index(fields=["claimed_at"], name="sms_rate_idx"),
                ],
            },
        ),
    ]
