# Generated by Django 6.1 on 2026-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsconfig",
            name="template_selection",
            field=models.JSONField(default=dict),
        ),
    ]
