# Generated by Django 6.1 on 2026-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_crm", "0002_smsconfig_template_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsdelivery",
            name="last_polled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
