# Generated by Django 6.1 on 2026-09-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_crm", "0003_smsdelivery_last_polled_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsProviderSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("username_ciphertext", models.TextField(blank=True)),
                ("password_ciphertext", models.TextField(blank=True)),
                ("sender", models.CharField(blank=True, max_length=32)),
                ("body_ids", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
