import { useCallback, useEffect, useState } from 'react';
import { api, toman } from '../shared/api';
import './AdminSMS.css';

const root = 'admin/sms/';
const unwrap = value => value?.results || value || [];
const tabs = [['campaigns', 'کمپین‌ها'], ['customers', 'مخاطبان و وفاداری'], ['loyalty', 'پیامک‌های وفادارسازی'], ['automations', 'پیامک‌های خودکار'], ['reports', 'گزارش ارسال'], ['settings', 'تنظیمات پیامک']];
const statuses = {draft:'پیش‌نویس', scheduled:'زمان‌بندی شده', queued:'در صف', sending:'در حال ارسال', sent:'پذیرفته‌شده برای ارسال', delivered:'تحویل‌شده', failed:'ناموفق', unknown:'نیاز به بررسی', cancelled:'لغو شده', completed:'پردازش تمام شده'};
const kinds = {birthday:'تولد', service_reminder:'یادآوری ترمیم سرویس', inactive:'بازگشت مشتری غیرفعال', appointment_reminder:'یادآوری نوبت', appointment_created:'ثبت نوبت', appointment_confirmed:'تأیید نوبت', appointment_changed:'تغییر نوبت', appointment_cancelled:'لغو نوبت'};
const deliveryKinds = {marketing:'تبلیغاتی', transactional:'مربوط به نوبت', management:'گزارش مدیریت', test:'آزمایش'};
const variables = ['first_name', 'service_name', 'booking_link', 'discount_code', 'salon_name', 'appointment_date', 'appointment_time'];
const errorText = err => { const data = err.response?.data; return data ? Object.values(data).flat().join(' · ') : 'ارتباط برقرار نشد؛ دوباره تلاش کنید.'; };
const dateText = value => value ? new Date(value).toLocaleString('fa-IR') : '—';
const defaultCampaign = {name:'', message:'', segment:{}, service:'', discount_code:'', booking_link:''};
const payload = form => ({...form, service:form.service || null, ...(Object.hasOwn(form,'category') ? {category:form.category || null} : {})});

function useResource(path) {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  const reload = useCallback(async () => {try {const r=await api.get(path);setData(r.data);setError('');}catch(e){setError(errorText(e));}}, [path]);
  useEffect(() => {reload();}, [reload]);
  return {data, error, reload};
}
function Status({value}) { return <span className={`sms-badge sms-${value}`}>{statuses[value] || '—'}</span>; }
function Empty({children='هنوز موردی ثبت نشده است.'}) { return <p className="sms-empty">{children}</p>; }
function Field({label, children}) { return <label className="sms-field"><span>{label}</span>{children}</label>; }
function Options({items}) { return <><option value="">همه / بدون انتخاب</option>{items.map(s => <option key={s.id} value={s.id}>{s.persian_name || s.name || [s.first_name,s.last_name].join(' ')}</option>)}</>; }

function SegmentSummary({segment={}, resources}) {
  const labels={service:'سرویس', category:'دسته', employee:'متخصص', inactive_days:'روز بدون مراجعه', min_visits:'حداقل نوبت انجام‌شده', min_spend:'حداقل پرداخت تومان', new_days:'عضویت در روزهای اخیر', visited_after:'مراجعه از', visited_before:'مراجعه تا'};
  const lists={service:resources.services,category:resources.categories,employee:resources.employees};
  const parts=Object.entries(segment).map(([key,value])=>{const item=lists[key]?.find(s=>s.id===Number(value));return `${labels[key] || ''}: ${item?.persian_name || item?.name || value}`;});
  return <span>{parts.join(' · ') || 'همه مشتریان دارای رضایت'}</span>;
}

function SegmentBuilder({value, onChange, services, categories, employees}) {
  const change = (key, input, numeric=false) => {const next = {...value}; if (input === '') delete next[key]; else next[key] = numeric ? Number(input) : input; onChange(next);};
  return <fieldset className="sms-segment"><legend>مخاطبان بر اساس سوابق واقعی سالن</legend><div className="sms-fields">
    {[['service','سرویس انجام‌شده',services],['category','دسته خدمات',categories],['employee','متخصص',employees]].map(([key,label,items]) => <Field key={key} label={label}><select value={value[key] || ''} onChange={e=>change(key,e.target.value,true)}><Options items={items} /></select></Field>)}
    {[['inactive_days','عدم مراجعه بیش از (روز)'],['min_visits','حداقل نوبت انجام‌شده'],['min_spend','حداقل پرداخت خالص (تومان)'],['new_days','عضویت در چند روز اخیر']].map(([key,label])=><Field key={key} label={label}><input type="number" min={key.startsWith('min_') ? 0 : 1} value={value[key] ?? ''} onChange={e=>change(key,e.target.value,true)} /></Field>)}
    {[['visited_after','مراجعه از تاریخ (میلادی)'],['visited_before','مراجعه تا تاریخ (میلادی)']].map(([key,label])=><Field key={key} label={label}><input type="date" value={value[key] || ''} onChange={e=>change(key,e.target.value)} /></Field>)}
  </div><small>فیلترها با هم اعمال می‌شوند. غیرفعال بودن از آخرین سرویس انجام‌شده محاسبه می‌شود؛ مشتری بدون سابقه مراجعه، غیرفعال فرض نمی‌شود.</small></fieldset>;
}

function MessageEditor({value, onChange}) {
  // Conservative UCS-2 estimate; authoritative per-recipient counts come from preview.
  const units = value.length;
  return <div><Field label="متن پیام"><textarea required maxLength={2000} rows={5} value={value} onChange={e=>onChange(e.target.value)} /></Field>
    <small>{[...value].length.toLocaleString('fa-IR')} نویسه · حدود {(!units ? 0 : units <= 70 ? 1 : Math.ceil(units/67)).toLocaleString('fa-IR')} بخش فارسی پیش از جایگزینی متغیرها و لینک لغو</small>
    <div className="sms-variables" aria-label="متغیرهای پیام">{variables.map(v=><button type="button" key={v} onClick={()=>onChange(value+`{{${v}}}`)}>{`{{${v}}}`}</button>)}</div>
    <small>نام سرویس، کد تخفیف و لینک فقط در صورت ثبت مقدار قابل استفاده‌اند. کد تخفیف صرفاً متن پیام است و مبلغ رزرو را تغییر نمی‌دهد.</small>
  </div>;
}

function DeliveryTable({rows}) {
  if (!rows.length) return <Empty>هنوز پیامی در این گزارش ثبت نشده است.</Empty>;
  return <div className="sms-table-wrap"><table><thead><tr><th>مخاطب / زمان</th><th>نوع</th><th>وضعیت</th><th>متن و نتیجه</th></tr></thead><tbody>{rows.map(d=><tr key={d.id}>
    <td><span dir="ltr">{d.phone}</span><small>{dateText(d.created_at)}</small>{d.campaign && <small>کمپین #{d.campaign}</small>}{d.appointment && <small>نوبت #{d.appointment}</small>}</td>
    <td>{deliveryKinds[d.kind]}{d.automation && <small>قانون #{d.automation}</small>}</td><td><Status value={d.status}/></td>
    <td><details><summary>مشاهده پیام و سابقه</summary><p className="sms-message">{d.message}</p><small>شناسه ارائه‌دهنده: {d.provider_message_id || '—'}</small><small>ارسال: {dateText(d.sent_at)} · تحویل: {dateText(d.delivered_at)}</small>{d.attempts?.map((a,i)=><small key={i}>{dateText(a.created_at)} · {statuses[a.status]} · {a.failure_reason}</small>)}</details>{d.failure_reason && <p>{d.failure_reason}</p>}</td>
  </tr>)}</tbody></table></div>;
}

function Campaigns({resources, notify, provider}) {
  const campaigns = useResource(root+'campaigns/');
  const [form,setForm] = useState(null), [busy,setBusy] = useState(false), [preview,setPreview] = useState(null), [selected,setSelected] = useState(null);
  const [schedule,setSchedule] = useState(''), [testPhone,setTestPhone] = useState('');
  const update = (k,v)=>setForm(f=>({...f,[k]:v}));
  const save = async e => {e.preventDefault(); setBusy(true); try {const response = form.id ? await api.patch(root+`campaigns/${form.id}/`,payload(form)) : await api.post(root+'campaigns/',payload(form)); setForm(null); setSelected(response.data); await campaigns.reload(); notify('پیش‌نویس ذخیره شد.');} catch(e){notify(errorText(e));} finally{setBusy(false);}};
  const inspect = async c => {setBusy(true); try {const r=await api.post(root+`campaigns/${c.id}/preview/`); setSelected(c); setPreview(r.data); setSchedule('');} catch(e){notify(errorText(e));}finally{setBusy(false);}};
  const confirm = async () => {setBusy(true); try {await api.post(root+`campaigns/${selected.id}/confirm/`,{confirmation_token:preview.confirmation_token, scheduled_at:schedule ? new Date(schedule).toISOString() : null});setPreview(null);await campaigns.reload();notify('کمپین در صف ارسال ثبت شد.');}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  const testSend = async () => {setBusy(true);try {await api.post(root+`campaigns/${selected.id}/test-send/`,{phone:testPhone});notify('پیام آزمایشی در صف ثبت شد؛ نتیجه را در گزارش ارسال ببینید.');}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  const cancel = async c => {setBusy(true);try{await api.post(root+`campaigns/${c.id}/cancel/`);await campaigns.reload();notify('پیام‌های ارسال‌نشده کمپین لغو شدند.');}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  return <><div className="sms-heading"><div><h2>کمپین‌های سالن</h2><p>ابتدا پیش‌نویس، سپس بررسی مخاطبان و تأیید ارسال.</p></div><button className="admin-primary" onClick={()=>{notify('');setForm({...defaultCampaign});}}>کمپین جدید</button></div>
    {campaigns.error && <p role="alert">{campaigns.error}</p>}{!campaigns.data ? <Empty>در حال دریافت…</Empty> : !unwrap(campaigns.data).length ? <Empty>اولین کمپین را با انتخاب سرویس و مشتریان مرتبط بسازید.</Empty> : <div className="sms-campaigns">{unwrap(campaigns.data).map(c=><article key={c.id} className="sms-card"><div className="sms-heading"><h3>{c.name}</h3><Status value={c.status}/></div><p className="sms-message">{c.message}</p><p>گروه هدف: <SegmentSummary segment={c.segment} resources={resources}/></p><small>{dateText(c.created_at)} · {c.created_by_name || 'مدیر'}{c.scheduled_at && ` · ارسال: ${dateText(c.scheduled_at)}`}</small><div className="sms-stats"><span>{c.report.total} مخاطب</span><span>{c.report.pending} در انتظار</span><span>{c.report.sent+c.report.delivered} پذیرفته‌شده</span><span>{c.report.failed} ناموفق</span><span>{c.report.unknown} نامشخص</span><span>{c.report.success_rate}٪ پذیرش ارسال</span></div><div className="sms-actions">{c.status==='draft' && <><button disabled={busy} onClick={()=>{notify('');setForm(c);}}>ویرایش</button><button disabled={busy} onClick={()=>inspect(c)}>بررسی و ارسال</button></>}<button onClick={()=>setSelected(c)}>آزمایش و جزئیات</button>{['draft','queued','scheduled'].includes(c.status) && <button disabled={busy} onClick={()=>cancel(c)}>توقف کمپین</button>}</div></article>)}</div>}
    {selected && !preview && !form && <section className="sms-card"><h3>{selected.name} — ارسال آزمایشی</h3><div className="sms-actions"><Field label="شماره آزمایشی"><input type="tel" dir="ltr" value={testPhone} onChange={e=>setTestPhone(e.target.value)} /></Field><button disabled={busy || !testPhone || !provider?.configured} onClick={testSend}>ارسال آزمایشی</button><button onClick={()=>setSelected(null)}>بستن</button></div><p>آزمایش به تعداد مخاطبان کمپین اضافه نمی‌شود. در حالت آزمایشی ارائه‌دهنده، ارسال واقعی ثبت نخواهد شد.</p><CampaignHistory id={selected.id}/></section>}
    {form && <div className="modal-backdrop"><form className="admin-modal sms-modal" onSubmit={save}><div className="sms-heading"><h2>{form.id ? 'ویرایش کمپین' : 'کمپین جدید'}</h2><button type="button" onClick={()=>setForm(null)}>بستن</button></div><Field label="نام کمپین"><input required maxLength={160} value={form.name} onChange={e=>update('name',e.target.value)}/></Field><MessageEditor value={form.message} onChange={v=>update('message',v)}/><div className="sms-fields"><Field label="سرویس مرتبط برای متن"><select value={form.service || ''} onChange={e=>update('service',e.target.value)}><Options items={resources.services}/></select></Field><Field label="کد تخفیف اختیاری"><input value={form.discount_code} onChange={e=>update('discount_code',e.target.value)}/></Field><Field label="لینک رزرو اختیاری"><input type="url" dir="ltr" value={form.booking_link} onChange={e=>update('booking_link',e.target.value)}/></Field></div><SegmentBuilder value={form.segment} onChange={v=>update('segment',v)} {...resources}/><button className="admin-primary" disabled={busy}>ذخیره پیش‌نویس</button></form></div>}
    {preview && <div className="modal-backdrop"><section className="admin-modal sms-modal" role="dialog" aria-modal="true" aria-label="تأیید ارسال کمپین"><h2>تأیید ارسال: {selected.name}</h2><div className="sms-stats"><strong>{preview.recipient_count} مخاطب</strong><strong>حدود {preview.total_parts} بخش پیامک</strong></div><p>گروه هدف: <SegmentSummary segment={selected.segment} resources={resources}/></p><p>فقط مشتریان دارای رضایت دریافت پیامک. لینک لغو به پیام هر مشتری اضافه می‌شود. فهرست زیر حداکثر ۵۰ مخاطب را نشان می‌دهد.</p><pre className="sms-message">{preview.audience[0]?.message || 'مخاطبی در این گروه وجود ندارد.'}</pre><div className="sms-audience-preview">{preview.audience.map(a=><p key={a.customer}>{a.name} · <span dir="ltr">{a.phone}</span> · {a.parts} بخش</p>)}</div><Field label="زمان ارسال (خالی = اکنون، ساعت دستگاه)"><input type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)}/></Field><p>ارسال در دسته‌های محدود توسط سرور انجام می‌شود. توقف کمپین، پیام‌های قبلاً ارسال‌شده را بازنمی‌گرداند.</p><div className="sms-actions"><button className="admin-primary" disabled={busy || !preview.recipient_count || !provider?.configured || provider?.marketing_ready===false} onClick={confirm}>تأیید و ارسال</button><button disabled={busy} onClick={()=>setPreview(null)}>بازگشت</button></div></section></div>}
  </>;
}

function CampaignHistory({id}) {const history=useResource(root+`deliveries/?campaign=${id}`);return <><p>سوابق کمپین</p>{history.error ? <p role="alert">{history.error}</p> : <DeliveryTable rows={unwrap(history.data)}/>}</>;}

function Customers({resources, notify}) {
  const [search,setSearch]=useState(''), [query,setQuery]=useState('');
  const customers=useResource(root+'customers/?search='+encodeURIComponent(query));
  const [segment,setSegment]=useState({}), [audience,setAudience]=useState(null), [profile,setProfile]=useState(null), [birth,setBirth]=useState(''), [evidence,setEvidence]=useState(''), [busy,setBusy]=useState(false);
  const inspect=async id=>{try{const r=await api.get(root+`customers/${id}/`);setProfile(r.data);setBirth(r.data.birth_date || '');setEvidence('');}catch(e){notify(errorText(e));}};
  const save=async data=>{setBusy(true);try{const r=await api.patch(root+`customers/${profile.id}/`,data);setProfile(r.data);await customers.reload();notify('اطلاعات مشتری ثبت شد.');}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  const preview=async()=>{setBusy(true);try{const r=await api.post(root+'audience/',segment);setAudience(r.data);}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  return <><h2>مخاطبان و وفاداری مشتریان</h2><SegmentBuilder value={segment} onChange={v=>{setSegment(v);setAudience(null);}} {...resources}/><button disabled={busy} onClick={preview}>بررسی مخاطبان دارای رضایت</button>{audience && <div className="sms-card"><h3>{audience.count} مخاطب واجد شرایط</h3><p>{audience.customers.map(c=>c.name).join('، ') || 'مخاطبی با این فیلترها و رضایت فعال وجود ندارد.'}</p></div>}
    <form className="sms-actions" onSubmit={e=>{e.preventDefault();setQuery(search);}}><Field label="جست‌وجوی مشتری"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام یا شماره تماس"/></Field><button>جست‌وجو</button></form>{customers.error && <p role="alert">{customers.error}</p>}<div className="sms-table-wrap"><table><thead><tr><th>مشتری</th><th>آخرین مراجعه</th><th>نوبت انجام‌شده</th><th>پرداخت خالص</th><th>پیامک تبلیغاتی</th><th></th></tr></thead><tbody>{unwrap(customers.data).map(c=><tr key={c.id}><td>{c.name}<small dir="ltr">{c.phone}</small></td><td>{c.last_visit || 'بدون مراجعه ثبت‌شده'}</td><td>{c.completed_appointments}</td><td>{toman(c.total_confirmed_spend)}</td><td>{c.marketing_sms_allowed?'مجاز':'غیرفعال'}</td><td><button onClick={()=>inspect(c.id)}>پرونده مشتری</button></td></tr>)}</tbody></table></div><small>حداکثر ۱۰۰ نتیجه نمایش داده می‌شود؛ برای یافتن مشتری جست‌وجو کنید.</small>
    {profile && <div className="drawer-backdrop"><aside className="admin-drawer sms-profile"><button onClick={()=>setProfile(null)}>بستن پرونده</button><h2>{profile.name}</h2><p dir="ltr">{profile.phone}</p><div className="sms-stats"><span>{profile.total_visits} مراجعه</span><span>{profile.total_appointments} نوبت</span><span>{profile.completed_appointments} انجام‌شده</span><span>{toman(profile.total_confirmed_spend)} پرداخت خالص تأییدشده</span></div><p>آخرین نوبت: {profile.last_appointment || '—'} · آخرین مراجعه: {profile.last_visit || '—'}</p><p>سرویس‌های پرتکرار: {profile.favorite_services.map(([n,c])=>`${n} (${c})`).join('، ') || '—'}</p><p>متخصصان پرتکرار: {profile.favorite_specialists.map(([n,c])=>`${n} (${c})`).join('، ') || '—'}</p><h3>ترجیحات ارتباطی</h3><p>{profile.marketing_sms_allowed?'دریافت تبلیغات فعال است.':'دریافت تبلیغات غیرفعال است.'}</p>{profile.opted_out_at && <p>لغو دریافت ثبت شده؛ فعال‌سازی دوباره فقط توسط خود مشتری امکان‌پذیر است.</p>}<Field label="تاریخ تولد اختیاری (میلادی؛ فقط با اطلاعات مشتری)"><input type="date" value={birth} onChange={e=>setBirth(e.target.value)}/></Field><button disabled={busy} onClick={()=>save({birth_date:birth || null})}>ثبت تاریخ تولد</button>{!profile.marketing_sms_allowed && !profile.opted_out_at && <><Field label="منبع و تاریخ رضایت صریح مشتری"><textarea value={evidence} onChange={e=>setEvidence(e.target.value)} maxLength={500}/></Field><button disabled={busy || !evidence.trim()} onClick={()=>save({marketing_sms_allowed:true,evidence})}>ثبت رضایت دریافت تبلیغات</button></>}{profile.marketing_sms_allowed && <button disabled={busy} onClick={()=>save({marketing_sms_allowed:false,evidence:'درخواست لغو ثبت‌شده توسط مدیر'})}>ثبت لغو دریافت تبلیغات</button>}<h3>سابقه رضایت</h3>{profile.consent_history.map((c,i)=><p key={i}>{dateText(c.created_at)} · {c.allowed?'فعال':'غیرفعال'} · {c.evidence}</p>)}<h3>تاریخچه پیامک (فقط خواندنی)</h3><DeliveryTable rows={profile.sms_history}/></aside></div>}
  </>;
}

function Automations({resources, notify, transactional}) {
  const rules=useResource(root+'automations/'), [form,setForm]=useState(null), [busy,setBusy]=useState(false);
  const update=(k,v)=>setForm(f=>({...f,[k]:v}));
  const save=async e=>{e.preventDefault();setBusy(true);try{if(form.id) {await api.patch(root+`automations/${form.id}/`,payload(form));} else {await api.post(root+'automations/',payload(form));}setForm(null);await rules.reload();notify('قانون ذخیره شد.');}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  const toggle=async r=>{setBusy(true);try{await api.patch(root+`automations/${r.id}/`,{enabled:!r.enabled});await rules.reload();}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  const visible=unwrap(rules.data).filter(r=>r.kind.startsWith('appointment_')===transactional);
  return <><div className="sms-heading"><div><h2>{transactional?'پیامک‌های مربوط به نوبت':'وفادارسازی و بازگشت مشتری'}</h2><p>{transactional?'یادآوری نوبت از تبلیغات جداست و زمان آن را شما تعیین می‌کنید.':'تولد فقط با تاریخ واقعی؛ ترمیم بر اساس آخرین سرویس انجام‌شده؛ بازگشت بر اساس آخرین مراجعه.'}</p></div><button className="admin-primary" onClick={()=>setForm({...defaultCampaign,kind:transactional?'appointment_reminder':'birthday',enabled:false,interval_days:30,hours_before:24,category:''})}>قانون جدید</button></div>{rules.error && <p role="alert">{rules.error}</p>}{!visible.length && <Empty>هنوز قانونی ثبت نشده است.</Empty>}<div className="sms-campaigns">{visible.map(r=><article className="sms-card" key={r.id}><h3>{r.name}</h3><p>{kinds[r.kind]} · {r.enabled?'فعال':'غیرفعال'}</p><p className="sms-message">{r.message}</p><small>آخرین اجرا: {dateText(r.last_run)} · بررسی بعدی: {r.next_expected_run ? dateText(r.next_expected_run) : 'وابسته به اجرای پردازشگر سرور'}</small><div className="sms-actions"><button onClick={()=>{notify('');setForm(r);}}>ویرایش</button><button disabled={busy} onClick={()=>toggle(r)}>{r.enabled?'غیرفعال کردن':'فعال کردن'}</button></div></article>)}</div>
    {form && <div className="modal-backdrop"><form className="admin-modal sms-modal" onSubmit={save}><div className="sms-heading"><h2>تنظیم قانون پیامک</h2><button type="button" onClick={()=>setForm(null)}>بستن</button></div><Field label="نام قانون"><input required value={form.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="نوع پیام"><select disabled={!!form.id} value={form.kind} onChange={e=>update('kind',e.target.value)}>{Object.entries(kinds).filter(([k])=>k.startsWith('appointment_')===transactional).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></Field><MessageEditor value={form.message} onChange={v=>update('message',v)}/><div className="sms-fields"><Field label="سرویس مرتبط"><select value={form.service || ''} onChange={e=>update('service',e.target.value)}><Options items={resources.services}/></select></Field><Field label="دسته خدمات"><select value={form.category || ''} onChange={e=>update('category',e.target.value)}><Options items={resources.categories}/></select></Field>{['service_reminder','inactive'].includes(form.kind) && <Field label="تعداد روز پس از مراجعه"><input type="number" min={1} max={3650} value={form.interval_days} onChange={e=>update('interval_days',Number(e.target.value))}/></Field>}{form.kind==='appointment_reminder' && <Field label="چند ساعت پیش از نوبت"><input type="number" min={1} max={168} value={form.hours_before} onChange={e=>update('hours_before',Number(e.target.value))}/></Field>}<Field label="لینک رزرو اختیاری"><input type="url" value={form.booking_link} onChange={e=>update('booking_link',e.target.value)}/></Field><Field label="کد پیشنهادی اختیاری"><input value={form.discount_code} onChange={e=>update('discount_code',e.target.value)}/></Field></div><SegmentBuilder value={form.segment} onChange={v=>update('segment',v)} {...resources}/><Field label="اجرای خودکار فعال باشد"><input type="checkbox" checked={form.enabled} onChange={e=>update('enabled',e.target.checked)}/></Field><button className="admin-primary" disabled={busy}>ذخیره قانون</button></form></div>}
  </>;
}

function Settings({data, reload, notify}) {
  const [form,setForm]=useState(data.settings), [busy,setBusy]=useState(false);
  const update=(k,v)=>setForm(f=>({...f,[k]:v}));
  const save=async e=>{e.preventDefault();setBusy(true);try{await api.patch(root+'settings/',form);await reload();notify('تنظیمات پیامک ثبت شد.');}catch(e){notify(errorText(e));}finally{setBusy(false);}};
  return <form className="sms-card" onSubmit={save}><h2>تنظیمات پیامک و گزارش مدیریت</h2><p>{data.provider.message}</p><p>اطلاعات اتصال ارائه‌دهنده توسط مسئول استقرار روی سرور تنظیم می‌شود.</p>{data.provider.marketing_ready===false && <p>نشانی عمومی HTTPS برای لینک لغو پیامک هنوز تنظیم نشده است؛ ارسال تبلیغات تا تنظیم آن غیرفعال است.</p>}<div className="sms-fields"><Field label="نام سالن در پیام"><input required value={form.salon_name} onChange={e=>update('salon_name',e.target.value)}/></Field><Field label="لینک پیش‌فرض رزرو"><input type="url" dir="ltr" value={form.booking_link} onChange={e=>update('booking_link',e.target.value)}/></Field><Field label="شماره دریافت گزارش مدیر"><input type="tel" dir="ltr" value={form.manager_phone} onChange={e=>update('manager_phone',e.target.value)}/></Field><Field label="ساعت گزارش روزانه (تهران)"><input type="number" min={0} max={23} value={form.daily_summary_hour} onChange={e=>update('daily_summary_hour',Number(e.target.value))}/></Field><Field label="حداکثر پیام در هر نوبت پردازش"><input type="number" min={1} max={100} value={form.batch_size} onChange={e=>update('batch_size',Number(e.target.value))}/></Field></div>{[['daily_summary_enabled','گزارش روزانه سالن'],['campaign_summary_enabled','گزارش پایان کمپین'],['failure_alert_enabled','هشدار خطای ارسال (حداکثر روزی یک بار)']].map(([k,l])=><Field key={k} label={l}><input type="checkbox" checked={form[k]} onChange={e=>update(k,e.target.checked)}/></Field>)}<button className="admin-primary" disabled={busy}>ذخیره تنظیمات</button></form>;
}

function Reports() {
  const [status,setStatus]=useState(''), [kind,setKind]=useState('');
  const reports=useResource(root+`deliveries/?status=${status}&kind=${kind}`);
  return <><div className="sms-heading"><h2>گزارش ارسال</h2><button onClick={reports.reload}>به‌روزرسانی</button></div><p>پذیرش ارسال به معنی تحویل نیست. نتیجه نامشخص نیاز به بررسی ارائه‌دهنده دارد و خودکار دوباره ارسال نمی‌شود.</p><div className="sms-fields"><Field label="وضعیت"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه</option>{['queued','sending','sent','delivered','failed','unknown','cancelled'].map(s=><option key={s} value={s}>{statuses[s]}</option>)}</select></Field><Field label="نوع پیام"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">همه</option>{Object.entries(deliveryKinds).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></Field></div>{reports.error ? <p role="alert">{reports.error}</p> : <DeliveryTable rows={unwrap(reports.data)}/>}</>;
}

export default function AdminSMS({initialTab='campaigns'}) {
  const [tab,setTab]=useState(initialTab), [message,setMessage]=useState('');
  const config=useResource(root+'settings/');
  const services=useResource('admin/services/'), categories=useResource('admin/service-categories/'), employees=useResource('admin/employees/');
  const resources={services:unwrap(services.data),categories:unwrap(categories.data),employees:unwrap(employees.data)};
  return <div className="admin-page sms-crm" dir="rtl"><header><span className="admin-kicker">ارتباط با مشتریان بهارناژ</span><h1>پیامک و ارتباط با مشتریان</h1><p>پیام مرتبط با سابقه مراجعه، با انتخاب و رضایت مشتری.</p></header>{message && <div className="sms-notice" role="status">{message}<button aria-label="بستن پیام" onClick={()=>setMessage('')}>×</button></div>}{[config.error,services.error,categories.error,employees.error].filter(Boolean).map((e,i)=><p role="alert" key={i}>{e}</p>)}{config.data && <div className="sms-provider"><strong>{config.data.provider.message}</strong><small>آخرین فعالیت پردازشگر: {dateText(config.data.settings.last_worker_at)}</small>{!config.data.worker_running && <p>پردازشگر فعال گزارش نشده است؛ پیام‌های صف تا اجرای آن ارسال نمی‌شوند.</p>}</div>}<nav className="sms-tabs" aria-label="بخش‌های ارتباط با مشتری">{tabs.map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setMessage('');}}>{label}</button>)}</nav><section className="admin-panel sms-content">{tab==='campaigns' && <Campaigns resources={resources} notify={setMessage} provider={config.data?.provider}/>} {tab==='customers' && <Customers resources={resources} notify={setMessage}/>} {['loyalty','automations'].includes(tab) && <Automations key={tab} resources={resources} notify={setMessage} transactional={tab==='automations'}/>} {tab==='reports' && <Reports/>} {tab==='settings' && config.data && <Settings data={config.data} reload={config.reload} notify={setMessage}/>}</section></div>;
}
