import Disclosure from '../components/TelegramDisclosure'
import { useCallback, useEffect, useRef, useState } from 'react'
import { api } from '../shared/api'
import { useSearchParams } from 'react-router-dom'
import { DateModal } from '../components/DatePicker'
import TelegramSetup from './TelegramSetup'
import TelegramHelp from './TelegramHelp'
import './AdminTelegram.css'
import '../components/Telegram.css'

const fa = value => new Intl.NumberFormat('fa-IR').format(value || 0)
const deliveryReason = key => ({expired:'زمان مناسب ارسال گذشته است',connection_unavailable:'اتصال در دسترس نیست',no_consent:'دریافت این پیام انتخاب نشده',promotional_cap:'فاصله مجاز پیام‌ها رعایت نشده',quiet_hours:'خارج از ساعت ارسال',audience_changed:'شرایط مشتری تغییر کرده',unreachable:'ربات مسدود یا در دسترس نیست',offer_inactive:'هدیه فعال نیست',network_outcome_unknown:'پاسخ قطعی از تلگرام دریافت نشد',stale_claim_outcome_unknown:'نتیجه ارسال قبلی مشخص نیست',automation_disabled:'این پیام خودکار خاموش است',obsolete_version:'نوبت تغییر کرده',telegram_permanent_error:'تلگرام پیام را نپذیرفت',telegram_5xx:'اختلال موقت تلگرام',rate_limited:'محدودیت موقت ارسال'})[key] || 'ارسال انجام نشد؛ وضعیت اتصال و تنظیمات را بررسی کنید'
const root = 'telegram/admin/'
const unwrap = d => d.results || d
const statuses = { queued: 'در صف', sending: 'در حال ارسال', accepted: 'پذیرفته‌شده توسط تلگرام', failed: 'ناموفق', unknown: 'نتیجه نامشخص', suppressed: 'ارسال نشده به دلیل محدودیت', cancelled: 'لغوشده', simulated: 'شبیه‌سازی', draft: 'پیش‌نویس', running: 'در حال اجرا', paused: 'متوقف', completed: 'پایان‌یافته' }
const errors = { unlinked: 'بدون اتصال حساب', unreachable: 'غیرقابل‌دسترس', no_consent: 'بدون رضایت تبلیغاتی', followup_suppression: 'توقف پس از بازخورد', cap: 'سقف پیام هفتگی' }
const dateInput = value => value ? new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Tehran', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date(value)).replace(' ', 'T') : ''
const localTime = value => value ? new Intl.DateTimeFormat('fa-IR', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Tehran' }).format(new Date(value)) : 'هنوز ثبت نشده'
function useData(endpoint) {
  const [page, setPage] = useState(1)
  const paginatedEndpoint = endpoint.includes('?') ? endpoint : endpoint + '?page=' + page
  const [state, setState] = useState({ data: null, error: '' })
  const requestId = useRef(0)
  const reload = useCallback(async () => { const id=++requestId.current; try { const {data}=await api.get(root+paginatedEndpoint); if(id===requestId.current) setState({data,error:''}) } catch {if(id===requestId.current) setState({data:null,error:'دریافت اطلاعات ممکن نشد.'})} },[paginatedEndpoint])
  useEffect(() => { let active=true; const id=++requestId.current; api.get(root+paginatedEndpoint).then(({data})=>{if(active && id===requestId.current)setState({data,error:''})}).catch(()=>{if(active && id===requestId.current)setState({data:null,error:'دریافت اطلاعات ممکن نشد.'})}); return () => {active=false} }, [paginatedEndpoint])
  return { ...state, reload, page, setPage }
}
function Pages({ resource }) {
  if (!resource.data?.results || (!resource.data.next && resource.page === 1)) return null
  return <div className="telegram-actions"><button disabled={resource.page===1} onClick={() => resource.setPage(resource.page-1)}>قبلی</button><span>صفحه {resource.page}</span><button disabled={!resource.data.next} onClick={() => resource.setPage(resource.page+1)}>بعدی</button></div>
}
function Audience({ value = {}, onChange, services = [] }) {
  const change = (k, v) => { const next = { ...value }; if (v === '' || v === false) delete next[k]; else next[k] = v; onChange(next) }
  return <fieldset className="tg-audience"><legend>گروه مشتریان</legend><label>یک گروه انتخاب کنید<select value={value.inactive_days ? 'inactive' : value.never_visited ? 'never' : Object.keys(value).length ? 'custom' : 'all'} onChange={e => onChange(e.target.value === 'inactive' ? {inactive_days:90} : e.target.value === 'never' ? {never_visited:true} : e.target.value === 'custom' ? {operator:'AND'} : {})}><option value="all">همه مشتریان موافق دریافت پیشنهاد</option><option value="inactive">مشتریانی که ۹۰ روز مراجعه نکرده‌اند</option><option value="never">مشتریانی که هنوز مراجعه نکرده‌اند</option><option value="custom">انتخاب بر اساس سرویس یا محله</option></select></label><Disclosure className="tg-disclosure" open={Object.keys(value).length > 0 || undefined}><summary>دقیق‌تر انتخاب کردن مخاطبان <span>اختیاری</span></summary><div className="tg-disclosure-body">{value.recipe && <p>برای گروه {value.recipe === 'hair_color' ? 'رنگ مو' : 'ناخن'}، سرویس یا دسته‌بندی واقعی کاتالوگ را انتخاب کنید.</p>}{Object.hasOwn(value, 'neighborhood') && value.neighborhood === '' && <p>فقط مشتریان با محله نامشخص انتخاب شده‌اند.</p>}<div className="telegram-grid">
    <label>ترکیب شرایط<select value={value.operator || 'AND'} onChange={e => change('operator', e.target.value)}><option value="AND">همه شرایط (و)</option><option value="OR">حداقل یک شرط (یا)</option></select></label>
    <label>سرویس انجام‌شده<select value={value.service_ids?.[0] || ''} onChange={e => change('service_ids', e.target.value ? [Number(e.target.value)] : '')}><option value="">همه سرویس‌ها</option>{services.map(s => <option key={s.id} value={s.id}>{s.persian_name || s.name}</option>)}</select></label>
    <label>دسته‌بندی سرویس<select value={value.category_ids?.[0] || ''} onChange={e => change('category_ids', e.target.value ? [Number(e.target.value)] : '')}><option value="">همه دسته‌ها</option>{[...new Map(services.filter(s => s.category).map(s => [s.category, s.category_name || `دسته ${s.category}`])).entries()].map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    <label>بازه سابقه سرویس (روز)<input type="number" min="1" max="3650" value={value.within_days || ''} onChange={e => change('within_days', e.target.value ? Number(e.target.value) : '')} /></label>
    <label>بدون مراجعه در چند روز اخیر؟<input type="number" min="1" max="3650" placeholder="۹۰" value={value.inactive_days || ''} onChange={e => change('inactive_days', e.target.value ? Number(e.target.value) : '')} /></label>
    <label>محله ثبت‌شده<input maxLength={120} value={value.neighborhood || ''} onChange={e => change('neighborhood', e.target.value)} /></label>
    <label className="telegram-check"><input type="checkbox" checked={!!value.never_visited} onChange={e => change('never_visited', e.target.checked)} />بدون سابقه مراجعه</label>
  </div></div></Disclosure><p className="tg-muted">مشتریان بدون اتصال حساب یا رضایت تبلیغاتی در فهرست ارسال قرار نمی‌گیرند. نوبت‌های پیش‌رو از گروه غیرفعال حذف می‌شوند.</p></fieldset>
}
function AudienceCounts({ data }) {
  return data && <div className="tg-audience-count" role="status"><strong>{fa(data.eligible)} مشتری آماده دریافت این پیام</strong><details><summary>چرا همه مشتریان در فهرست نیستند؟</summary><p>مشتریان این گروه: {fa(data.total)} · اتصال قابل‌دسترس: {fa(data.reachable)}</p>{Object.entries(data.exclusions || {}).map(([key,count]) => <p key={key}>{errors[key] || deliveryReason(key)}: {fa(count)}</p>)}</details></div>
}
function Overview({ navigate }) {
  const { data, error, reload } = useData('overview/')
  if (error) return <div className="tg-empty"><p role="alert">{error}</p><button onClick={reload}>تلاش دوباره</button></div>
  if (!data) return <p role="status">در حال دریافت وضعیت…</p>
  return <>
    <section className="tg-welcome"><div><span className="tg-eyebrow">ارتباط با مشتری، قدم‌به‌قدم</span><h2>{data.configured ? 'امروز چه کاری می‌خواهید انجام دهید؟' : 'ابتدا ربات سالن را وصل کنید'}</h2><p>{data.configured ? 'یک پیام آماده کنید یا یادآوری نوبت‌ها را تنظیم کنید.' : 'اطلاعات ربات را ذخیره کنید و اتصال را بررسی کنید. تا وقتی ارسال را فعال نکنید، پیامی فرستاده نمی‌شود.'}</p><button className="tg-primary" onClick={() => navigate(data.configured ? 'campaigns' : 'settings')}>{data.configured ? 'نوشتن پیام به مشتریان' : 'راه‌اندازی ربات'}</button></div><div className="tg-state"><span className="tg-state-dot" aria-hidden="true" /><strong>{!data.configured ? 'ارسال آماده نیست' : data.dry_run ? 'حالت آزمایشی' : 'ارسال واقعی فعال'}</strong><small>{data.dry_run ? 'پیام واقعی از سایت ارسال نمی‌شود' : 'فقط برای مشتریان موافق'}</small></div></section>
    <div className="tg-task-grid"><button onClick={() => navigate('campaigns')}><span className="tg-number">۱</span><strong>پیام به مشتریان</strong><span>متن، مخاطب و زمان را انتخاب کنید.</span><b aria-hidden="true">←</b></button><button onClick={() => navigate('automations')}><span className="tg-number">۲</span><strong>یادآوری نوبت‌ها</strong><span>سایت در زمان مناسب یادآوری می‌کند.</span><b aria-hidden="true">←</b></button><button onClick={() => navigate('help')}><span className="tg-number">؟</span><strong>راهنمای ساده</strong><span>هر کار را در چند قدم یاد بگیرید.</span><b aria-hidden="true">←</b></button></div>
    <section className="tg-section"><div className="tg-section-heading"><h2>وضعیت در یک نگاه</h2><button className="tg-text-button" onClick={reload}>به‌روزرسانی</button></div><div className="tg-metrics"><div><strong>{fa(data.linked)}</strong><span>اتصال ثبت‌شده</span></div><div><strong>{fa(data.eligible)}</strong><span>مشتری موافق پیام تبلیغاتی</span></div><div><strong>{fa(data.counts.queued || 0)}</strong><span>پیام در انتظار ارسال</span></div></div></section>
    <Disclosure className="tg-disclosure"><summary>گزارش ارسال‌ها و اجرای خودکار <span>جزئیات بیشتر</span></summary><div className="tg-disclosure-body"><p>آخرین اجرای خودکار: {localTime(data.heartbeat)}</p><p>ربات: <bdi>{data.bot_username ? '@'+data.bot_username : 'هنوز ثبت نشده'}</bdi></p>{Object.entries(data.counts).map(([key, count]) => <p key={key}>{statuses[key] || key}: {fa(count)}</p>)}<p>بازدید پیوند: {fa(data.link_visits)} · رزرو از پیوند پیام: {fa(data.attributed_bookings)} · نوبت انجام‌شده از پیوند: {fa(data.attributed_completed)} · تأیید دیدن یادآوری: {fa(data.acknowledgments)}</p><p className="tg-muted">«پذیرفته‌شده توسط تلگرام» به معنی خوانده شدن نیست. بازدید پیوند هم تأیید خواندن پیام توسط مشتری نیست.</p><h3>ارسال‌های بعدی</h3>{data.next_jobs.length ? data.next_jobs.map(j => <p key={j.id}>{({reminder:'یادآوری نوبت',status:'خبر نوبت',campaign:'پیام گروهی',birthday:'تبریک تولد',manager:'گزارش مدیر',care:'مراقبت سرویس',feedback:'نظرخواهی',maintenance:'پیگیری مراجعه',loyalty:'امتیاز',reactivation:'دعوت به مراجعه',test:'نمونه برای مدیر'})[j.kind] || 'پیام'} · {localTime(j.scheduled_at)}</p>) : <p>پیامی در صف نیست.</p>}</div></Disclosure>
  </>
}
function Customers({ services,act }) {
  const [page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[filters,setFilters]=useState({}),[applied,setApplied]=useState(null),[preview,setPreview]=useState(null),[name,setName]=useState(''),[points,setPoints]=useState(null)
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setPage(1)},300);return()=>clearTimeout(timer)},[search])
  const customers=useData(`customers/?page=${page}&search=${encodeURIComponent(query)}${applied?'&filters='+encodeURIComponent(JSON.stringify(applied)):''}`),segments=useData('segments/')
  return <><h2>مشتریان و انتخاب پیام‌ها</h2><p className="tg-muted">این صفحه فقط وضعیت را نشان می‌دهد؛ دریافت پیام را خود مشتری انتخاب می‌کند.</p><label>جست‌وجوی مشتری<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام یا محله مشتری"/></label>
    <Disclosure className="tg-disclosure"><summary>دیدن یک گروه از مشتریان <span>{applied?'فیلتر فعال است':'انتخاب بر اساس سابقه، سرویس یا محله'}</span></summary><div className="tg-disclosure-body"><div className="telegram-actions">{segments.data&&unwrap(segments.data).map(segment=><button key={segment.id} onClick={()=>setFilters(segment.filters)}>{segment.name}</button>)}<button onClick={()=>setFilters({recipe:'hair_color',service_ids:[],within_days:180})}>مشتریان رنگ مو</button><button onClick={()=>setFilters({recipe:'nails',service_ids:[],within_days:180})}>مشتریان ناخن</button><button onClick={()=>setFilters({neighborhood:''})}>محله نامشخص</button></div><Audience value={filters} onChange={setFilters} services={services}/><div className="telegram-actions"><button className="tg-primary" onClick={()=>{setApplied(filters);setPage(1)}}>نمایش این گروه</button><button onClick={()=>{setApplied(null);setPage(1)}}>نمایش همه مشتریان</button><button onClick={()=>act(()=>api.post(root+'segments/preview/',{filters}).then(({data})=>setPreview(data)),'')}>چند نفر پیام می‌گیرند؟</button></div><AudienceCounts data={preview}/><details><summary>این گروه را برای دفعات بعد نگه دارم</summary><label>نام گروه<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً مشتریان رنگ مو"/></label><button disabled={!name.trim()} onClick={()=>act(()=>api.post(root+'segments/',{name,filters}).then(segments.reload),'گروه ذخیره شد.')}>ذخیره گروه</button></details></div></Disclosure>
    {customers.error&&<p role="alert">{customers.error}</p>}{!customers.data&&!customers.error&&<p role="status">در حال دریافت مشتریان…</p>}{customers.data&&(unwrap(customers.data).length?<div className="tg-list">{unwrap(customers.data).map(c=><article className="tg-customer" key={c.id}><div className="tg-section-heading"><h3>{c.name}</h3><span className="tg-badge">{c.connected?'متصل به ربات':'هنوز متصل نشده'}</span></div><p className="tg-muted">{c.marketing?'دریافت پیشنهاد را انتخاب کرده':'دریافت پیشنهاد را انتخاب نکرده'} · {c.neighborhood||'محله ثبت نشده'}</p><details><summary>جزئیات مشتری</summary><p>{fa(c.completed_visits)} مراجعه انجام‌شده · {fa(c.points_balance)} امتیاز</p><div className="telegram-actions"><button onClick={()=>act(()=>api.get(root+`customers/${c.id}/points/`).then(({data})=>setPoints({name:c.name,data})),'')}>دیدن گردش امتیاز</button><button onClick={()=>{const neighborhood=window.prompt('محله‌ای که مشتری اعلام کرده است:',c.neighborhood||'');if(neighborhood!==null)act(()=>api.post(root+`customers/${c.id}/neighborhood/`,{neighborhood}).then(customers.reload))}}>ثبت یا اصلاح محله</button></div></details></article>)}</div>:<div className="tg-empty"><h3>مشتری مطابق این جست‌وجو پیدا نشد</h3><p>نام دیگری وارد کنید یا فیلتر گروه را بردارید.</p></div>)}
    {(page>1||customers.data?.next)&&<div className="telegram-actions"><button disabled={page===1} onClick={()=>setPage(page-1)}>قبلی</button><span>صفحه {fa(page)}</span><button disabled={!customers.data?.next} onClick={()=>setPage(page+1)}>بعدی</button></div>}
    {points&&<section className="tg-section"><div className="tg-section-heading"><h3>گردش امتیاز {points.name}</h3><button onClick={()=>setPoints(null)}>بستن</button></div>{unwrap(points.data).length?unwrap(points.data).map(p=><p key={p.id}>{fa(p.delta)} امتیاز · {p.reason} · {localTime(p.created_at)}</p>):<p>هنوز امتیازی ثبت نشده است.</p>}{points.data.next&&<button onClick={()=>act(()=>api.get(points.data.next).then(({data})=>setPoints({...points,data})), '')}>صفحه بعد گردش امتیاز</button>}</section>}
  </>
}
function Campaigns({ services, act }) {
  const list = useData('campaigns/'), offers = useData('benefit-rules/')
  const blank = { name: '', text: '', filters: {}, service: null, offer: null, terms: '' }
  const [form, setForm] = useState(blank), [id, setId] = useState(null), [step, setStep] = useState(0)
  const [preview, setPreview] = useState(null), [results, setResults] = useState(null), [confirmed, setConfirmed] = useState(false), [dateOpen, setDateOpen] = useState(false)
  const stepHeading=useRef(null)
  useEffect(()=>{if(step){stepHeading.current?.focus({preventScroll:true});stepHeading.current?.scrollIntoView?.({block:'nearest'})}},[step])
  const [sendDay, setSendDay] = useState(''), [sendTime, setSendTime] = useState('10:00')
  const change = (k,v) => { setForm({ ...form, [k]: v }); setPreview(null); setConfirmed(false) }
  const start = c => { setForm(c || blank); setId(c?.id || null); setPreview(null); setConfirmed(false); setStep(1); setSendDay(c?.scheduled_at ? dateInput(c.scheduled_at).slice(0,10) : ''); setSendTime(c?.scheduled_at ? dateInput(c.scheduled_at).slice(11,16) : '10:00') }
  const persist = async () => {
    const body = { ...form, name: form.name.trim() || form.text.trim().slice(0,45), scheduled_at: sendDay ? `${sendDay}T${sendTime}:00+03:30` : new Date().toISOString() }
    const { data } = await (id ? api.patch(root+`campaigns/${id}/`, body) : api.post(root+'campaigns/', body))
    setId(data.id); setForm(data); await list.reload(); return data
  }
  const review = () => act(async () => { const saved=await persist(); const {data}=await api.post(root+`campaigns/${saved.id}/preview/`); setPreview(data); setConfirmed(false); setStep(3) }, '')
  return <>
    {step === 0 ? <div className="tg-section-heading"><div><h2>پیام‌های شما</h2><p>هر پیام را پیش از ارسال بررسی و تأیید می‌کنید.</p></div><button className="tg-primary" onClick={() => start()}>＋ نوشتن پیام</button></div> : <section className="tg-composer"><div className="tg-section-heading"><h2 ref={stepHeading} tabIndex={-1}>آماده کردن پیام</h2><button onClick={() => { if(window.confirm('ویرایش‌های ذخیره‌نشده کنار گذاشته شوند؟')) setStep(0) }}>بستن</button></div>
      <ol className="tg-steps" aria-label="مراحل آماده‌سازی پیام">{['متن پیام','انتخاب مشتریان','بررسی و ارسال'].map((label,i) => <li key={label} aria-current={step===i+1 ? 'step' : undefined}><span>{fa(i+1)}</span>{label}</li>)}</ol>
      {step===1 && <div className="tg-form-section"><h3>چه پیامی می‌خواهید بفرستید؟</h3><label>متن پیام<textarea rows={5} maxLength={3500} value={form.text} onChange={e => change('text',e.target.value)} placeholder="سلام، برای دیدن زمان‌های خالی و رزرو نوبت، دکمه زیر را بزنید." /></label><p className="tg-muted">کوتاه و روشن بنویسید. دکمه رزرو به پیام اضافه می‌شود.</p><label>عنوان برای خودتان <span className="tg-muted">اختیاری؛ مشتری این عنوان را نمی‌بیند</span><input maxLength={100} value={form.name} onChange={e => change('name',e.target.value)} placeholder="مثلاً: زمان‌های خالی این هفته" /></label><label>دکمه رزرو به کجا برود؟<select value={form.service || ''} onChange={e => change('service',e.target.value ? Number(e.target.value) : null)}><option value="">صفحه رزرو همه سرویس‌ها</option>{services.map(service => <option key={service.id} value={service.id}>{service.persian_name}</option>)}</select></label><Disclosure className="tg-disclosure"><summary>افزودن تخفیف به پیام <span>اختیاری</span></summary><div className="tg-disclosure-body"><p>ابتدا هدیه واقعی را در بخش یادآوری‌ها و هدیه‌ها تعریف کنید. نوشتن عدد تخفیف در متن، قیمت را تغییر نمی‌دهد.</p><label>هدیه تعریف‌شده<select value={form.offer || ''} onChange={e => change('offer',e.target.value ? Number(e.target.value) : null)}><option value="">بدون تخفیف</option>{offers.data && unwrap(offers.data).map(o => <option key={o.id} value={o.id}>{o.name} · {o.enabled ? 'فعال' : 'غیرفعال'}</option>)}</select></label>{form.offer && <label>شرایط استفاده<input maxLength={500} value={form.terms} onChange={e => change('terms',e.target.value)} placeholder="سرویس‌های مشمول و مهلت استفاده" /></label>}</div></Disclosure><div className="tg-wizard-footer"><button className="tg-primary" disabled={!form.text.trim()} onClick={() => setStep(2)}>بعدی: انتخاب مشتریان ←</button><button disabled={!form.text.trim()} onClick={() => act(async () => { await persist(); setStep(0) }, 'پیش‌نویس ذخیره شد؛ پیامی ارسال نشده است.')}>ذخیره برای بعد</button></div></div>}
      {step===2 && <div className="tg-form-section"><h3>چه کسانی این پیام را دریافت کنند؟</h3><Audience value={form.filters} onChange={v => change('filters',v)} services={services} /><h3>چه زمانی ارسال شود؟</h3><p className="tg-muted">اگر روزی انتخاب نکنید، پیام در نزدیک‌ترین ساعت مجاز وارد صف می‌شود.</p><div className="telegram-grid"><div><label>روز ارسال</label><button className="tg-date" onClick={() => setDateOpen(true)}>{sendDay ? new Date(sendDay+'T12:00:00+03:30').toLocaleDateString('fa-IR') : 'انتخاب روز — اختیاری'}</button>{sendDay && <button className="tg-text-button" onClick={() => setSendDay('')}>نزدیک‌ترین زمان مجاز</button>}</div>{sendDay && <label>ساعت به وقت تهران<input type="time" value={sendTime} onChange={e => setSendTime(e.target.value)} /></label>}</div>{dateOpen && <DateModal value={sendDay} onChange={setSendDay} onClose={() => setDateOpen(false)} />}<div className="tg-wizard-footer"><button onClick={() => setStep(1)}>→ مرحله قبل</button><button className="tg-primary" disabled={!!sendDay && !sendTime} onClick={review}>بعدی: بررسی پیام ←</button></div></div>}
      {step===3 && preview && <div className="tg-form-section"><h3>قبل از ارسال، یک بار بخوانید</h3><div className="tg-message-preview"><span>پیش‌نمایش پیام مشتری</span><p>{preview.text}</p><div>رزرو نوبت ←</div></div><AudienceCounts data={preview} /><p><strong>زمان درخواستی:</strong> {localTime(preview.scheduled_at)}</p><p className="tg-muted">ارسال در ساعت مجاز و با رعایت فاصله پیام‌ها انجام می‌شود. اگر ارسال سایت متوقف یا آزمایشی باشد، پیام واقعی ارسال نمی‌شود.</p>{preview.offer_terms && <div className="tg-notice"><p>تخفیف: {preview.offer_terms.percent ? `${preview.offer_terms.percent}٪` : `${preview.offer_terms.fixed} تومان`} · سقف: {preview.offer_terms.maximum || 'بدون سقف'} · پایان: {localTime(preview.offer_terms.ends_at)}</p><p>{preview.terms}</p></div>}<button onClick={() => { if(window.confirm('نمونه این پیام فقط برای حساب مدیر متصل خودتان در صف قرار بگیرد؟')) act(() => api.post(root+`campaigns/${id}/test/`, {confirm:true,request_id:crypto.randomUUID()}), 'نمونه در صف حساب مدیر قرار گرفت. در حالت آزمایشی، پیام واقعی ارسال نمی‌شود.') }}>اول یک نمونه برای خودم</button><label className="telegram-check tg-confirm"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />متن و زمان را بررسی کردم؛ ارسال برای {fa(preview.eligible)} مشتری را تأیید می‌کنم.</label>{!preview.eligible && <p className="tg-notice">در این گروه، مشتری آماده دریافت پیام نیست. گروه دیگری انتخاب کنید یا اتصال و رضایت مشتریان را بررسی کنید.</p>}<div className="tg-wizard-footer"><button onClick={() => {setStep(2);setConfirmed(false)}}>→ ویرایش مخاطب و زمان</button><button className="tg-primary" disabled={!confirmed || !preview.eligible} onClick={() => act(async () => { await api.post(root+`campaigns/${id}/schedule/`, {confirm:true,recipient_count:preview.eligible,revision:preview.revision}); setStep(0);setPreview(null);await list.reload() }, 'پیام در صف قرار گرفت. وضعیت آن را در فهرست زیر ببینید.')}>تأیید و قرار دادن در صف</button></div></div>}
    </section>}
    {step===0 && <>{list.error && <p role="alert">{list.error}</p>}{!list.data && !list.error && <p role="status">در حال دریافت پیام‌ها…</p>}{list.data && (unwrap(list.data).length ? <div className="tg-list">{unwrap(list.data).map(c => <article className="tg-list-row" key={c.id}><div><h3>{c.name}</h3><p>{c.text.slice(0,100)}{c.text.length>100?'…':''}</p><span className="tg-badge">{statuses[c.status]}</span></div><div className="telegram-actions"><button onClick={() => start(c)}>{c.status==='draft' ? 'ادامه نوشتن' : 'ساخت نسخه تازه'}</button><button onClick={() => act(() => api.get(root+`campaigns/${c.id}/results/`).then(({data}) => setResults({name:c.name,rows:data})), '')}>گزارش</button>{['queued','running','paused'].includes(c.status) && <><button onClick={() => act(() => api.post(root+`campaigns/${c.id}/control/`, {action:c.status==='paused'?'queued':'paused'}).then(list.reload), 'وضعیت پیام تغییر کرد.')}>{c.status==='paused'?'ادامه ارسال':'توقف'}</button><button onClick={() => { if(window.confirm('ارسال‌های منتظر این پیام لغو شوند؟ پیام‌های قبلی بازگردانده نمی‌شوند.')) act(() => api.post(root+`campaigns/${c.id}/control/`, {action:'cancelled'}).then(list.reload), 'ارسال‌های باقی‌مانده لغو شدند.') }}>لغو باقی‌مانده</button></>}</div></article>)}</div> : <div className="tg-empty"><h3>هنوز پیامی آماده نکرده‌اید</h3><p>با «نوشتن پیام» شروع کنید. تا تأیید شما، چیزی ارسال نمی‌شود.</p></div>)}<Pages resource={list} />{results && <section className="tg-section" role="status"><div className="tg-section-heading"><h3>گزارش «{results.name}»</h3><button onClick={() => setResults(null)}>بستن گزارش</button></div>{results.rows.length ? results.rows.map((r,i) => <p key={i}>{statuses[r.status] || r.status}: {fa(r.count)}{r.error && ` — ${deliveryReason(r.error)}`}</p>) : <p>هنوز ارسالی ثبت نشده است.</p>}</section>}</>}
  </>
}
function Fields({ fields,value,onChange,services=[] }) {
  return <div className="telegram-grid">{fields.map(([key,label,type])=> type==='services' ? <fieldset className="tg-unboxed" key={key}><legend>{label}</legend><div className="tg-service-options">{services.map(service=><label className="telegram-check" key={service.id}><input type="checkbox" checked={(value[key]||[]).includes(service.id)} onChange={e=>onChange({...value,[key]:e.target.checked?[...(value[key]||[]),service.id]:(value[key]||[]).filter(id=>id!==service.id)})}/>{service.persian_name}</label>)}</div></fieldset> : <label key={key} className={type==='checkbox'?'telegram-check':''}>{type==='checkbox'?<><input type="checkbox" checked={!!value[key]} onChange={e=>onChange({...value,[key]:e.target.checked})}/>{label}</>:<>{label}{type==='service'?<select value={value[key]||''} onChange={e=>onChange({...value,[key]:Number(e.target.value)})}><option value="">انتخاب سرویس</option>{services.map(service=><option key={service.id} value={service.id}>{service.persian_name}</option>)}</select>:type==='textarea'?<textarea value={value[key]||''} onChange={e=>onChange({...value,[key]:e.target.value})}/>:<input type={type||'text'} value={type==='datetime-local'?dateInput(value[key]):(value[key]??'')} onChange={e=>onChange({...value,[key]:type==='number'?Number(e.target.value):type==='datetime-local'&&e.target.value?`${e.target.value}:00+03:30`:e.target.value})}/>}</>}</label>)}</div>
}
function ResourceEditor({ endpoint, fields, initial, services, act, title, allowCreate = true }) {
  const list = useData(endpoint+'/'), [value, setValue] = useState(initial), [id, setId] = useState(null), [cost, setCost] = useState(null), [editing, setEditing] = useState(false)
  return <section className="tg-resource"><div className="tg-section-heading"><h3>{title}</h3>{allowCreate && !editing && <button onClick={() => { setId(null); setValue(initial); setEditing(true) }}>＋ افزودن</button>}</div>{editing && <><Fields fields={fields} value={value} onChange={setValue} services={services} /><div className="telegram-actions"><button disabled={!allowCreate && !id} onClick={() => act(() => (id ? api.patch(root+`${endpoint}/${id}/`, value) : api.post(root+endpoint+'/', value)).then(() => { setId(null); setValue(initial); setEditing(false); list.reload() }))}>ذخیره</button><button onClick={() => setEditing(false)}>انصراف</button></div></>}{list.error && <p role="alert">{list.error}</p>}{list.data && unwrap(list.data).map(item => <div className="telegram-row" key={item.id}><span>{({ pending: 'دریافت درخواست', confirmed: 'تأیید نوبت', cancelled: 'لغو نوبت', rescheduled: 'تغییر زمان', reminder: 'یادآوری', birthday: 'تولد', maintenance: 'پیگیری سرویس', feedback: 'بازخورد', loyalty: 'امتیاز', reactivation: 'بازگشت مشتری' }[item.name] || item.name) || services.find(s => s.id === item.service)?.persian_name || `#${item.id}`} {Object.hasOwn(item, 'enabled') && (item.enabled ? '· فعال' : '· غیرفعال')}</span><button onClick={() => { setId(item.id); setValue(item); setEditing(true) }}>ویرایش</button>{endpoint === 'benefit-rules' && <button onClick={() => act(() => api.get(root+`benefit-rules/${item.id}/preview/`).then(({ data }) => setCost(data)))}>پیش‌نمایش هزینه و شرایط</button>}</div>)}{cost && <div className="telegram-message"><strong>{cost.name}</strong><p>اعتبار: {localTime(cost.starts_at)} تا {localTime(cost.ends_at)} · سقف هر استفاده: {cost.maximum || 'وابسته به قیمت نهایی'} · تک‌مصرف و غیرقابل‌تجمیع</p>{cost.services.map((s,i) => <p key={i}>{s.service} · {s.estimated ? 'برآورد تخفیف' : 'تخفیف'}: {s.discount_from ?? 'پس از تعیین قیمت'} {s.discount_to !== null && s.discount_to !== s.discount_from ? `تا ${s.discount_to}` : ''} تومان</p>)}</div>}<Pages resource={list} /></section>
}
function ConfigForm({ group = 'limits', act }) {
  const resource=useData('config/'), rules=useData('benefit-rules/')
  return resource.data ? <ConfigEditor key={JSON.stringify(resource.data)} initial={resource.data} resource={resource} group={group} act={act} rules={rules.data ? unwrap(rules.data) : []} /> : <p role="status">{resource.error || 'در حال دریافت تنظیمات…'}</p>
}
function ConfigEditor({ initial,resource,group,act,rules }) {
  const [value,setValue]=useState(initial)
  const groups={
    birthday:[['birthday_enabled','ارسال تبریک تولد','checkbox']],
    points:[['points_per_toman','هر چند تومان پرداخت = یک امتیاز؟ (صفر یعنی خاموش)','number'],['points_expiry_days','اعتبار امتیاز، به روز','number']],
    reactivation:[['reactivation_enabled','دعوت مشتریان قدیمی به مراجعه','checkbox'],['reactivation_days','بعد از چند روز بدون مراجعه؟','number']],
    reports:[['manager_daily','خلاصه نوبت‌های روز برای مدیر','checkbox'],['manager_cancellations','خلاصه لغوهای روز قبل برای مدیر','checkbox'],['manager_failures','گزارش پیام‌های ناموفق برای مدیر','checkbox']],
    contact:[['hours','ساعت کار سالن'],['map_url','پیوند نقشه','url'],['instagram_url','پیوند اینستاگرام','url'],['support_url','پیوند تماس یا پشتیبانی','url']],
    limits:[['marketing_start','شروع ساعت ارسال پیام اختیاری (تهران)','number'],['marketing_end','پایان ساعت ارسال پیام اختیاری (تهران)','number'],['cap_days','حداقل چند روز بین پیام‌های تبلیغاتی فاصله باشد؟','number'],['attribution_days','رزرو تا چند روز بعد از باز کردن پیوند، مربوط به پیام شمرده شود؟','number']],
  }
  const fields=groups[group] || []
  const save=()=>{ const keys=fields.map(([key])=>key);if(group==='appointments')keys.push('status_events','reminder_hours');if(group==='birthday')keys.push('birthday_gift');act(()=>api.patch(root+'config/',Object.fromEntries(keys.map(key=>[key,value[key]]))).then(resource.reload)) }
  return <div className="tg-form-section">
    {group==='appointments' && <><p>این پیام‌ها فقط برای مشتریانی ارسال می‌شوند که دریافت یادآوری را انتخاب کرده‌اند.</p><fieldset className="tg-unboxed"><legend>خبرهای نوبت</legend>{[['pending','دریافت درخواست رزرو'],['confirmed','تأیید نوبت'],['rescheduled','تغییر زمان نوبت'],['cancelled','لغو نوبت']].map(([key,label])=><label className="telegram-check" key={key}><input type="checkbox" checked={(value.status_events || []).includes(key)} onChange={e=>setValue({...value,status_events:e.target.checked?[...(value.status_events || []),key]:value.status_events.filter(v=>v!==key)})}/>{label}</label>)}</fieldset><fieldset className="tg-unboxed"><legend>چه زمانی یادآوری شود؟</legend>{[[24,'یک روز پیش از نوبت'],[3,'سه ساعت پیش از نوبت']].map(([hours,label])=><label className="telegram-check" key={hours}><input type="checkbox" checked={(value.reminder_hours || []).includes(hours)} onChange={e=>setValue({...value,reminder_hours:e.target.checked?[...value.reminder_hours,hours]:value.reminder_hours.filter(v=>v!==hours)})}/>{label}</label>)}</fieldset><Disclosure className="tg-disclosure"><summary>زمان‌های دیگر <span>در صورت نیاز</span></summary><div className="tg-disclosure-body"><label>ساعت‌های قبل از نوبت، با ویرگول انگلیسی<input value={(value.reminder_hours || []).join(',')} onChange={e=>setValue({...value,reminder_hours:e.target.value.split(',').filter(Boolean).map(Number)})}/></label><p>مثال: 24,3 یعنی یک روز و سه ساعت قبل. حداکثر پنج زمان انتخاب کنید.</p></div></Disclosure></>}
    {group==='points' && <p className="tg-notice">فعال کردن امتیاز، نوبت‌های واجد شرایط قبلی را هم بررسی می‌کند. با هر بازپرداخت یا لغو، امتیاز آن نوبت کامل برمی‌گردد.</p>}
    {group==='birthday' && <p>تولد اختیاری است. اگر هدیه‌ای انتخاب نکنید، فقط تبریک ارسال می‌شود.</p>}
    <Fields fields={fields} value={value} onChange={setValue}/>
    {group==='birthday' && <label>هدیه تولد<select value={value.birthday_gift || ''} onChange={e=>setValue({...value,birthday_gift:e.target.value?Number(e.target.value):null})}><option value="">فقط تبریک، بدون هدیه</option>{rules.map(r=><option key={r.id} value={r.id}>{r.name} · {r.enabled?'فعال':'غیرفعال'}</option>)}</select></label>}
    <button className="tg-primary" onClick={()=>{if(group!=='points' || window.confirm('قانون امتیاز با شرایط نمایش‌داده‌شده ذخیره شود؟'))save()}}>ذخیره این تنظیمات</button>
  </div>
}
function Automations({ services,act }) {
  const benefits=useData('benefits/'),previews=useData('automation-preview/')
  return <><h2>یادآوری‌ها و هدیه‌ها</h2><p className="tg-muted">فقط بخش مورد نیازتان را باز کنید. امکانات اختیاری تا انتخاب شما خاموش می‌مانند.</p>
    <Disclosure className="tg-disclosure"><summary>یادآوری نوبت‌ها <span>خبر رزرو، تغییر زمان و یادآوری پیش از مراجعه</span></summary><div className="tg-disclosure-body"><ConfigForm group="appointments" act={act}/></div></Disclosure>
    <Disclosure className="tg-disclosure"><summary>تبریک تولد <span>تبریک ساده یا همراه با هدیه</span></summary><div className="tg-disclosure-body"><ConfigForm group="birthday" act={act}/></div></Disclosure>
    <Disclosure className="tg-disclosure"><summary>پیگیری پس از سرویس <span>مراقبت، نظرخواهی و یادآوری مراجعه بعدی</span></summary><div className="tg-disclosure-body"><p>متن مراقبت و فاصله مراجعه بعدی را کارکنان سالن تعیین می‌کنند. صفر یعنی بدون یادآوری مراجعه بعدی.</p><ResourceEditor title="سرویس‌های دارای پیگیری" endpoint="service-rules" fields={[["service","سرویس","service"],['enabled','این پیگیری فعال باشد','checkbox'],['interval_days','چند روز بعد از انجام سرویس یادآوری شود؟','number'],['aftercare','متن مراقبت تأییدشده توسط کارکنان','textarea'],['feedback','یک‌بار نظر مشتری پرسیده شود','checkbox']]} initial={{enabled:false,interval_days:0,aftercare:'',feedback:false}} services={services} act={act}/><details><summary>زمان پیگیری‌های بعدی</summary><button onClick={previews.reload}>به‌روزرسانی</button>{previews.data?.service_rules?.map(r=><p key={r.id}>{r.service} · {r.enabled?'فعال':'خاموش'} · {r.next_preview?localTime(r.next_preview):'هنوز سابقه یا زمان مناسب ثبت نشده'}</p>)}</details></div></Disclosure>
    <Disclosure className="tg-disclosure"><summary>دعوت مشتریان قدیمی <span>پیام برای مشتریانی که مدتی مراجعه نکرده‌اند</span></summary><div className="tg-disclosure-body"><p>فقط برای مشتریان موافق پیام تبلیغاتی که نوبت پیش‌رو ندارند.</p><ConfigForm group="reactivation" act={act}/></div></Disclosure>
    <Disclosure className="tg-disclosure"><summary>امتیاز وفاداری <span>امتیاز برای نوبت‌های انجام‌شده و تسویه‌شده</span></summary><div className="tg-disclosure-body"><ConfigForm group="points" act={act}/></div></Disclosure>
    <Disclosure className="tg-disclosure"><summary>هدیه و تخفیف شخصی <span>تعریف شرایط و ثبت استفاده از هدیه</span></summary><div className="tg-disclosure-body"><p>هدیه‌ها برای همان مشتری، یک‌بار و بدون جمع شدن با هدیه دیگر قابل استفاده‌اند. پیش از فعال کردن، هزینه و شرایط را بررسی کنید.</p><ResourceEditor title="هدیه‌های تعریف‌شده" endpoint="benefit-rules" fields={[["name","نام هدیه"],['enabled','هدیه قابل استفاده باشد','checkbox'],['starts_at','شروع اعتبار (تاریخ میلادی، ساعت تهران)','datetime-local'],['ends_at','پایان اعتبار (تاریخ میلادی، ساعت تهران)','datetime-local'],['services','سرویس‌های مشمول','services'],['percent','درصد تخفیف (یا مبلغ ثابت)','number'],['fixed','مبلغ ثابت تخفیف، تومان','number'],['maximum','سقف تخفیف، تومان (صفر: بدون سقف)','number'],['points_cost','امتیاز لازم برای دریافت (صفر: بدون تبدیل امتیاز)','number']]} initial={{name:'',enabled:false,services:[],percent:0,fixed:0,maximum:0,points_cost:0}} services={services} act={act}/><h3>هدیه‌های مشتریان</h3>{benefits.data && (unwrap(benefits.data).length?unwrap(benefits.data).map(b=><div className="telegram-row" key={b.id}><span>هدیه {fa(b.id)} · {b.redeemed_at?`استفاده‌شده: ${fa(b.discount)} تومان`:new Date(b.terms.ends_at)<new Date()?'منقضی شده':b.reserved_for?`رزروشده برای نوبت ${fa(b.reserved_for)}`:'آماده استفاده'}</span>{b.reserved_for&&!b.redeemed_at&&<button onClick={()=>{if(window.confirm('تخفیف روی قیمت نهایی نوبت و پیش از پرداخت ثبت شود؟'))act(()=>api.post(root+`benefits/${b.id}/redeem/`,{confirm:true}).then(benefits.reload))}}>ثبت استفاده و اعمال تخفیف</button>}</div>):<p>هنوز هدیه‌ای برای مشتری صادر نشده است.</p>)}<Pages resource={benefits}/></div></Disclosure>
  </>
}
function ManagerRecipients({ act }) {
  const resource = useData('managers/')
  return <section><h3>گیرندگان تأییدشده مدیریت</h3>{resource.data && (Array.isArray(resource.data) && resource.data.length ? resource.data.map(c => <label className="telegram-check" key={c.id}><input type="checkbox" checked={c.selected} onChange={e => { const selected = e.target.checked; if (window.confirm(`گزارش‌های مدیریت برای ${c.name} ${selected ? 'فعال' : 'متوقف'} شود؟`)) act(() => api.post(root+'managers/', { id: c.id, selected }).then(resource.reload)) }} />{c.name} · {c.reachable ? 'قابل‌دسترس' : 'غیرقابل‌دسترس'}</label>) : <p>مدیر ابتدا باید از حساب خودش اتصال را تأیید کند.</p>)}</section>
}
export default function AdminTelegram() {
  const [params,setParams] = useSearchParams()
  const sections = [['overview','شروع'],['campaigns','پیام به مشتریان'],['automations','یادآوری‌ها'],['customers','مشتریان'],['settings','تنظیمات ربات']]
  const selected = params.get('section') || 'overview'
  const tab = [...sections.map(([key]) => key),'help'].includes(selected) ? selected : 'overview'
  const [message,setMessage] = useState(null), [busy,setBusy] = useState(false), [services,setServices] = useState([])
  const [campaignMounted,setCampaignMounted]=useState(tab==='campaigns')
  const heading=useRef(null), noticeRef=useRef(null)
  useEffect(()=>{if(message)noticeRef.current?.scrollIntoView?.({block:'nearest'})},[message])
  useEffect(() => { let active=true; api.get('services/').then(({data}) => { if(active) setServices(unwrap(data)) }).catch(() => { if(active) setMessage({error:true,text:'فهرست سرویس‌ها دریافت نشد. صفحه را تازه کنید.'}) }); return () => {active=false} }, [])
  const navigate = (section,topic) => { if(section==='campaigns')setCampaignMounted(true); setParams({ section, ...(topic?{topic}:{}) }); setMessage(null); requestAnimationFrame(() => {heading.current?.focus({preventScroll:true}); window.scrollTo?.(0,0)}) }
  const act = async (fn,success='تغییرات ذخیره شد.') => { setBusy(true);setMessage(null);try { await fn();if(success) setMessage({text:success});return true } catch(e) {const data=e.response?.data;setMessage({error:true,text:typeof data?.detail==='string'?data.detail:data?Object.values(data).flat().join('؛ '):'ارتباط برقرار نشد. دوباره تلاش کنید.'});return false} finally {setBusy(false)} }
  const topics={overview:'start',campaigns:'messages',automations:'reminders',customers:'delivery',settings:'start'}
  return <div className="telegram-admin telegram-panel"><header className="tg-header"><div><span className="tg-eyebrow">بهارناژ / ارتباط با مشتری</span><h1 ref={heading} tabIndex={-1}>تلگرام سالن</h1><p>یادآوری نوبت و پیام‌های کوتاه برای مشتریان شما</p></div><button className={tab==='help'?'tg-help-button active':'tg-help-button'} onClick={() => navigate('help')}><span aria-hidden="true">؟</span> راهنما</button></header>
    <nav className="telegram-tabs" aria-label="بخش‌های تلگرام">{sections.map(([key,label]) => <button key={key} aria-pressed={tab===key} onClick={() => navigate(key)}>{label}</button>)}</nav>
    <main className="tg-content">{tab!=='help' && <div className="tg-context-help"><button className="tg-text-button" onClick={() => navigate('help',topics[tab])}>این بخش چطور کار می‌کند؟</button></div>}{message && <p ref={noticeRef} role={message.error?'alert':'status'} className={message.error?'tg-notice tg-error':'tg-notice'}>{message.text}</p>}<fieldset disabled={busy} className="tg-unboxed" aria-busy={busy}>
      {tab==='overview' && <Overview navigate={navigate} />}{(campaignMounted || tab==='campaigns') && <div hidden={tab!=='campaigns'}><Campaigns services={services} act={act} /></div>}{tab==='customers' && <Customers services={services} act={act} />}{tab==='automations' && <Automations services={services} act={act} />}
      {tab==='settings' && <><TelegramSetup onHelp={topic => navigate('help',topic)} /><Disclosure className="tg-disclosure"><summary>ساعت ارسال و اطلاعات سالن <span>نشانی، تماس و محدودیت پیام‌ها</span></summary><div className="tg-disclosure-body"><ConfigForm group="contact" act={act} /><Disclosure className="tg-disclosure"><summary>ساعت و فاصله پیام‌ها</summary><div className="tg-disclosure-body"><ConfigForm group="limits" act={act} /></div></Disclosure></div></Disclosure><Disclosure className="tg-disclosure"><summary>متن پیام‌های خودکار <span>ویرایش متن‌های آماده</span></summary><div className="tg-disclosure-body"><p>برای شروع نیازی به تغییر متن‌ها نیست. {'{name}'} نام مشتری را خودکار می‌گذارد. عبارت‌های داخل آکولاد را پاک یا عوض نکنید.</p><ResourceEditor allowCreate={false} title="متن‌های آماده" endpoint="templates" fields={[['text','متن پیام','textarea']]} initial={{name:'',text:''}} act={act} /></div></Disclosure><Disclosure className="tg-disclosure"><summary>گزارش‌های مدیران <span>انتخاب گیرندگان گزارش</span></summary><div className="tg-disclosure-body"><ConfigForm group="reports" act={act} /><ManagerRecipients act={act} /></div></Disclosure></>}
      {tab==='help' && <TelegramHelp topic={params.get('topic')} navigate={navigate} />}
    </fieldset></main>
  </div>
}
