import { useEffect, useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { DateModal } from '../components/DatePicker'
import { api, toman } from '../shared/api'
import { useServices } from '../shared/hooks'
const steps = ['خدمات', 'متخصص', 'زمان', 'اطلاعات', 'تأیید']
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tehran' }).format(new Date())
const unwrap = (data) => data?.results || data || []
function WizardHeader({ step }) { return <div className="wizard-header"><span>رزرو آنلاین</span><div>{steps.map((label, index) => <div className={index <= step ? 'active' : ''} key={label}><b>{index + 1}</b><small>{label}</small></div>)}</div></div> }
function Back({ onClick }) { return <button type="button" className="wizard-back" onClick={onClick}>→ بازگشت</button> }
function Next({ children = 'ادامه', disabled = false, onClick }) { return <button className="button wizard-next" disabled={disabled} onClick={onClick}>{children} <span>←</span></button> }
function EmptyLine({ text }) { return <p className="wizard-empty">{text}</p> }

export default function Booking() {
  const { services } = useServices(); const params = new URLSearchParams(useLocation().search); const navigate = useNavigate()
  const [step, setStep] = useState(params.get('service') ? 1 : 0); const [selected, setSelected] = useState(params.get('service') ? [params.get('service')] : []); const [employees, setEmployees] = useState({}); const [employeeIds, setEmployeeIds] = useState({}); const [date, setDate] = useState(''); const [time, setTime] = useState(''); const [slots, setSlots] = useState([]); const [dateOpen, setDateOpen] = useState(false); const [contact, setContact] = useState({ name: '', phone: '', notes: '', account: false }); const [hold, setHold] = useState(null); const [confirmation, setConfirmation] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const chosenServices = useMemo(() => selected.map((id) => services.find((service) => String(service.id) === String(id))).filter(Boolean), [selected, services]); const total = chosenServices.reduce((sum, service) => sum + Number(service.price || 0), 0)
  useEffect(() => { selected.forEach((serviceId) => { if (!employees[serviceId]) api.get(`employees/?service=${serviceId}`).then(({ data }) => setEmployees((current) => ({ ...current, [serviceId]: unwrap(data) }))).catch(() => setEmployees((current) => ({ ...current, [serviceId]: [] }))) }) }, [selected, employees])
  useEffect(() => { if (!date || chosenServices.length !== selected.length || Object.keys(employeeIds).length !== selected.length) return; Promise.all(selected.map((serviceId) => api.get(`availability/?service=${serviceId}&employee=${employeeIds[serviceId]}&date=${date}`).then(({ data }) => data.slots || []).catch(() => []))).then((results) => setSlots(results.reduce((common, current) => common.filter((slot) => current.includes(slot)), results[0] || []))) }, [date, selected, employeeIds, chosenServices.length])
  useEffect(() => () => { if (hold) api.delete(`booking-holds/${hold.token}/`).catch(() => {}) }, [hold])
  const toggleService = (id) => setSelected((current) => current.includes(String(id)) ? current.filter((value) => value !== String(id)) : [...current, String(id)])
  const reserveHold = async () => { setError(''); setLoading(true); try { const duration = chosenServices.reduce((sum, service) => sum + Number(service.duration || 0), 0); const [hour, minute] = time.split(':').map(Number); const end = new Date(2000, 0, 1, hour, minute + duration); const endTime = `${String(end.getHours()).padStart(2, '0')}:${String(end.getMinutes()).padStart(2, '0')}`; const { data } = await api.post('booking-holds/', { employee: employeeIds[selected[0]], service: selected[0], date, start_time: time, end_time: endTime }); setHold(data); setStep(3) } catch (requestError) { setError(requestError.response?.data?.detail || 'این زمان دیگر در دسترس نیست.') } finally { setLoading(false) } }
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const duration = chosenServices.reduce((sum, service) => sum + Number(service.duration || 0), 0); const [hour, minute] = time.split(':').map(Number); const end = new Date(2000, 0, 1, hour, minute + duration); const endTime = `${String(end.getHours()).padStart(2, '0')}:${String(end.getMinutes()).padStart(2, '0')}`; const { data } = await api.post('appointments/', { customer_name: contact.name, customer_phone: contact.phone, notes: contact.notes, create_account: contact.account, account_password: contact.password, hold_token: hold?.token, items: selected.map((serviceId) => ({ service: serviceId, employee: employeeIds[serviceId], date, start_time: time, end_time: endTime })) }); setConfirmation(data); setHold(null); setStep(4) } catch (requestError) { setError(requestError.response?.data?.detail || 'ثبت رزرو انجام نشد. زمان دیگری را امتحان کنید.') } finally { setLoading(false) } }
  if (confirmation) return <Confirmation appointment={confirmation} navigate={navigate} />
  return <section className="booking-wizard container"><WizardHeader step={step} /><div className="wizard-intro"><p className="eyebrow">وقت تو، همین حالا</p><h1>{step === 0 ? 'خدمتت را انتخاب کن.' : step === 1 ? 'متخصصت را انتخاب کن.' : step === 2 ? 'زمان مناسب را پیدا کن.' : step === 3 ? 'اطلاعات تماس' : 'تأیید نهایی'}</h1><p>می‌توانی چند خدمت را در یک نوبت انتخاب کنی؛ ساعت‌ها بر اساس برنامه واقعی سالن نمایش داده می‌شوند.</p></div>{error && <p className="error wizard-error">{error}</p>}{step === 0 && <ServiceStep services={services} selected={selected} toggle={toggleService} onNext={() => setStep(1)} />}{step === 1 && <EmployeeStep selected={selected} services={chosenServices} employees={employees} employeeIds={employeeIds} setEmployeeIds={setEmployeeIds} onBack={() => setStep(0)} onNext={() => setStep(2)} />}{step === 2 && <TimeStep date={date} setDate={(value) => { setDate(value); setTime(''); setSlots([]) }} dateOpen={dateOpen} setDateOpen={setDateOpen} slots={slots} time={time} setTime={setTime} onBack={() => setStep(1)} onNext={reserveHold} loading={loading} />} {step === 3 && <ContactStep contact={contact} setContact={setContact} chosenServices={chosenServices} total={total} date={date} time={time} hold={hold} onBack={() => { setHold(null); setStep(2) }} onNext={() => setStep(4)} />}{step === 4 && <ReviewStep contact={contact} chosenServices={chosenServices} total={total} date={date} time={time} onBack={() => setStep(3)} onSubmit={submit} loading={loading} />}</section>
}
function ServiceStep({ services, selected, toggle, onNext }) { const groups = services.reduce((result, service) => { const key = service.category_name || service.category?.name || 'خدمات بهارناژ'; (result[key] ||= []).push(service); return result }, {}); return <div className="wizard-panel"><div className="category-groups">{Object.entries(groups).map(([category, items]) => <section key={category}><h2>{category}</h2><div className="service-choice-grid">{items.map((service) => <button type="button" className={selected.includes(String(service.id)) ? 'selected' : ''} onClick={() => toggle(service.id)} key={service.id}><span>{selected.includes(String(service.id)) ? '✓' : '＋'}</span><strong>{service.persian_name || service.name}</strong><small>{service.duration} دقیقه · {toman(service.price)}</small></button>)}</div></section>)}</div>{!services.length && <p className="empty-panel">خدمتی برای رزرو وجود ندارد.</p>}<div className="wizard-footer"><span>{selected.length} خدمت انتخاب شده</span><Next disabled={!selected.length} onClick={onNext}>انتخاب متخصص</Next></div></div> }
function EmployeeStep({ selected, services, employees, employeeIds, setEmployeeIds, onBack, onNext }) { const complete = selected.every((id) => employeeIds[id]); return <div className="wizard-panel"><div className="employee-choices">{services.map((service) => <section key={service.id}><h2>{service.persian_name || service.name}</h2><div className="employee-choice-grid">{(employees[service.id] || []).map((employee) => <button type="button" className={String(employeeIds[service.id]) === String(employee.id) ? 'selected' : ''} key={employee.id} onClick={() => setEmployeeIds((current) => ({ ...current, [service.id]: employee.id }))}><div className="employee-photo">{(employee.name || 'م')[0]}</div><strong>{employee.name || 'متخصص بهارناژ'}</strong><small>{employee.specialty || 'متخصص زیبایی'}</small></button>)}</div>{!employees[service.id]?.length && <EmptyLine text="متخصص فعالی برای این خدمت پیدا نشد." />}</section>)}</div><div className="wizard-footer"><Back onClick={onBack} /><Next disabled={!complete} onClick={onNext}>انتخاب تاریخ و ساعت</Next></div></div> }
function TimeStep({ date, setDate, dateOpen, setDateOpen, slots, time, setTime, onBack, onNext, loading }) { return <div className="wizard-panel"><label className="wizard-label">تاریخ نوبت<button type="button" className="date-trigger" onClick={() => setDateOpen(true)}>{date ? new Intl.DateTimeFormat('fa-IR', { timeZone: 'Asia/Tehran' }).format(new Date(`${date}T00:00:00Z`)) : 'انتخاب تاریخ'}</button></label>{dateOpen && <DateModal value={date || today()} onChange={setDate} onClose={() => setDateOpen(false)} />}{date && <><div className="slot-heading"><h2>ساعت‌های آزاد</h2><span>برنامه تهران</span></div>{slots.length ? <div className="slot-grid">{slots.map((slot) => <button type="button" className={time === slot ? 'selected' : ''} onClick={() => setTime(slot)} key={slot}>{slot}</button>)}</div> : <EmptyLine text="در این تاریخ ساعتی پیدا نشد. تاریخ دیگری را امتحان کنید." />}</>}<div className="wizard-footer"><Back onClick={onBack} /><Next disabled={!date || !time || loading} onClick={onNext}>{loading ? 'در حال بررسی...' : 'ادامه'}</Next></div></div> }
function ContactStep({ contact, setContact, chosenServices, total, date, time, hold, onBack, onNext }) { return <form className="wizard-panel contact-panel" onSubmit={(event) => { event.preventDefault(); onNext() }}><div className="hold-notice">این زمان تا ۵ دقیقه برای شما نگه داشته شده است.</div><div className="booking-summary"><span>{chosenServices.map((service) => service.persian_name || service.name).join(' + ')}</span><b>{date} · {time}</b><strong>{toman(total)}</strong></div><label>نام و نام خانوادگی<input required value={contact.name} onChange={(event) => setContact({ ...contact, name: event.target.value })} autoComplete="name" /></label><label>شماره موبایل<input required type="tel" pattern="(?:\+98|0098|0)9[0-9]{9}" value={contact.phone} onChange={(event) => setContact({ ...contact, phone: event.target.value })} placeholder="0912..." autoComplete="tel" /></label><label>یادداشت یا ترجیح خاص<textarea value={contact.notes} onChange={(event) => setContact({ ...contact, notes: event.target.value })} /></label><label className="check-label"><input type="checkbox" checked={contact.account} onChange={(event) => setContact({ ...contact, account: event.target.checked })} /> ساخت حساب کاربری برای مشاهده سوابق رزرو</label>{contact.account && <label>رمز عبور حساب<input required minLength="8" type="password" value={contact.password || ''} onChange={(event) => setContact({ ...contact, password: event.target.value })} /></label>}<div className="wizard-footer"><Back onClick={onBack} /><Next disabled={!hold}>بررسی اطلاعات</Next></div></form> }
function ReviewStep({ contact, chosenServices, total, date, time, onBack, onSubmit, loading }) { return <form className="wizard-panel contact-panel" onSubmit={onSubmit}><div className="booking-summary"><span>{chosenServices.map((service) => service.persian_name || service.name).join(' + ')}</span><b>{contact.name} · {contact.phone}</b><b>{date} · {time}</b><strong>{toman(total)}</strong></div><p className="wizard-empty">اطلاعات رزرو را بررسی کنید. با ثبت نهایی، درخواست شما برای سالن ارسال می‌شود.</p><div className="wizard-footer"><Back onClick={onBack} /><Next disabled={loading}>{loading ? 'در حال ثبت...' : 'ثبت نهایی رزرو'}</Next></div></form> }
function Confirmation({ appointment, navigate }) { return <section className="booking-confirmation container"><p className="eyebrow">رزرو با موفقیت ثبت شد</p><h1>منتظرت هستیم.</h1><p>کد پیگیری شما: <strong>{appointment.confirmation_code}</strong></p><div className="confirmation-card"><h2>جزئیات نوبت</h2>{appointment.items?.map((item) => <div key={item.id}><b>{item.service_name || 'خدمت بهارناژ'}</b><span>{item.date} · {item.start_time} تا {item.end_time}</span></div>)}</div><button className="button" onClick={() => navigate('/')}>بازگشت به خانه <span>←</span></button></section> }
