import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { DateModal } from '../components/DatePicker'
import { api, toman } from '../shared/api'
import { useServices } from '../shared/hooks'

// Booking coordinates per-service specialists and derives common availability slots.
export default function Booking() {
  const { services } = useServices(); const params = new URLSearchParams(useLocation().search)
  const [serviceRows, setServiceRows] = useState([{ serviceId: params.get('service') || '', employeeId: '' }]); const [employeesByService, setEmployeesByService] = useState({}); const [slots, setSlots] = useState([]); const [dateOpen, setDateOpen] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ name: '', phone: '', date: '', time: '' })
  useEffect(() => { serviceRows.forEach(({ serviceId }) => { if (serviceId && !employeesByService[serviceId]) api.get(`employees/?service=${serviceId}`).then(({ data }) => setEmployeesByService((current) => ({ ...current, [serviceId]: Array.isArray(data) ? data : data.results || [] }))).catch(() => setEmployeesByService((current) => ({ ...current, [serviceId]: [] }))) }) }, [serviceRows, employeesByService])
  useEffect(() => { const selectedRows = serviceRows.filter((row) => row.serviceId && row.employeeId); if (!form.date || selectedRows.length !== serviceRows.length) return; Promise.all(selectedRows.map((row) => api.get(`availability/?service=${row.serviceId}&employee=${row.employeeId}&date=${form.date}`).then(({ data }) => data.slots || []).catch(() => []))).then((availability) => setSlots(availability.reduce((common, current) => common.filter((slot) => current.includes(slot)), availability[0] || []))) }, [serviceRows, form.date])
  const totalPrice = serviceRows.reduce((total, row) => total + (services.find((item) => String(item.id) === row.serviceId)?.price || 0), 0); const complete = serviceRows.every((row) => row.serviceId && row.employeeId)
  const updateRow = (index, changes) => { setSlots([]); setForm((current) => ({ ...current, time: '' })); setServiceRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, ...changes } : row)) }; const addService = () => setServiceRows((current) => [...current, { serviceId: '', employeeId: '' }]); const removeService = (index) => setServiceRows((current) => current.length === 1 ? [{ serviceId: '', employeeId: '' }] : current.filter((_, rowIndex) => rowIndex !== index))
  const submit = async (event) => { event.preventDefault(); setError(''); try { await api.post('appointments/', { customer_name: form.name, customer_phone: form.phone, service: serviceRows[0].serviceId, services: serviceRows.map((row) => row.serviceId), service_assignments: serviceRows.map((row) => ({ service: row.serviceId, employee: row.employeeId })), employee: serviceRows[0].employeeId, date: form.date, start_time: form.time }); setDone(true) } catch { setError('این زمان در دسترس نیست یا اطلاعات کامل نشده است. لطفاً زمان دیگری را انتخاب کنید.') } }
  if (done) return <div className="page-intro container"><p className="eyebrow">رزرو بهارناژ</p><h1>درخواستت ثبت شد.</h1><p>برای هماهنگی نهایی، به‌زودی با شما تماس می‌گیریم.</p></div>
  return <section className="booking container"><div><p className="eyebrow">وقت تو، همین حالا</p><h1>نوبتت را<br /><em>رزرو کن.</em></h1><p>خدمت، متخصص، تاریخ و ساعت دلخواهت را انتخاب کن.</p></div><form onSubmit={submit}><div className="booking-services"><div className="field-heading"><span>خدمت و متخصص</span><button type="button" onClick={addService}>افزودن خدمت +</button></div>{serviceRows.map((row, index) => <div className="service-row" key={`${index}-${row.serviceId}`}><select required aria-label="خدمت" value={row.serviceId} onChange={(event) => updateRow(index, { serviceId: event.target.value, employeeId: '' })}><option value="">انتخاب خدمت</option>{services.filter((item) => !serviceRows.some((other, otherIndex) => otherIndex !== index && String(item.id) === other.serviceId)).map((item) => <option key={item.id} value={item.id}>{item.persian_name} · {toman(item.price)}</option>)}</select><select required aria-label="متخصص این خدمت" value={row.employeeId} disabled={!row.serviceId} onChange={(event) => updateRow(index, { employeeId: event.target.value })}><option value="">متخصص این خدمت</option>{(employeesByService[row.serviceId] || []).map((item) => <option key={item.id} value={item.id}>{item.name || 'متخصص بهارناژ'} · {item.specialty}</option>)}</select><button type="button" className="remove-service" onClick={() => removeService(index)} aria-label="حذف خدمت">×</button></div>)}</div><p className="booking-total">مجموع: {toman(totalPrice)}</p><label>تاریخ نوبت<button type="button" className="date-trigger" onClick={() => setDateOpen(true)}>{form.date ? new Intl.DateTimeFormat('fa-IR').format(new Date(`${form.date}T00:00:00`)) : 'انتخاب تاریخ'}</button></label>{dateOpen && <DateModal value={form.date} onChange={(date) => { setSlots([]); setForm({ ...form, date, time: '' }) }} onClose={() => setDateOpen(false)} />}<label>ساعت <span className="field-hint">ساعات کاری: ۰۸:۰۰ تا ۲۰:۰۰</span><select required value={form.time} onChange={(event) => setForm({ ...form, time: event.target.value })}><option value="">{!complete ? 'ابتدا خدمت و متخصص را انتخاب کنید' : !form.date ? 'ابتدا تاریخ را انتخاب کنید' : 'در حال دریافت زمان‌های خالی...'}</option>{(complete && form.date ? slots : []).map((slot) => <option key={slot} value={slot}>{slot}</option>)}</select></label><label>نام و نام خانوادگی<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="مثلاً مریم احمدی" /></label><label>شماره تماس<input required type="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="۰۹۱۲۱۲۳۴۵۶۷" /></label>{error && <p className="error">{error}</p>}<button className="button" type="submit">تأیید رزرو <span>←</span></button></form></section>
}
