import { useEffect, useState } from 'react'
import { api } from '../shared/api'

// Gallery owns filtering and lightbox state; the API remains the source of image data.
export default function Gallery() {
  const [items, setItems] = useState([])
  const [categoryOptions, setCategoryOptions] = useState([])
  const [category, setCategory] = useState('همه')
  const [activeItem, setActiveItem] = useState(null)
  const [state, setState] = useState('loading')
  useEffect(() => { Promise.all([api.get('gallery/'), api.get('gallery/categories/')]).then(([gallery, categories]) => { setItems(Array.isArray(gallery.data) ? gallery.data : gallery.data.results || []); setCategoryOptions(Array.isArray(categories.data) ? categories.data : categories.data.results || []); setState('ready') }).catch(() => setState('error')) }, [])
  useEffect(() => { document.body.style.overflow = activeItem ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [activeItem])
  const categories = ['همه', ...categoryOptions.map((item) => item.name)]
  const visibleItems = category === 'همه' ? items : items.filter((item) => item.category === category)
  return <section className="gallery-page container"><div className="gallery-intro"><p className="eyebrow">لحظه‌های بهارناژ</p><h1>گالری <em>ما.</em></h1><p>جزئیات کوچک زیبایی، آرامش و دقتی که در بهارناژ جریان دارد.</p></div>{state === 'loading' && <p className="gallery-state">در حال دریافت تصاویر...</p>}{state === 'error' && <p className="gallery-state error">دریافت تصاویر گالری ممکن نیست. لطفاً دوباره تلاش کنید.</p>}{state === 'ready' && !items.length && <p className="gallery-state">هنوز تصویری برای نمایش ثبت نشده است.</p>}{state === 'ready' && items.length > 0 && <><nav className="gallery-filters" aria-label="دسته‌بندی گالری">{categories.map((item) => <button className={category === item ? 'active' : ''} key={item} type="button" onClick={() => setCategory(item)}>{item}</button>)}</nav>{visibleItems.length ? <div className="gallery-grid">{visibleItems.map((item, index) => <button className={`gallery-card gallery-card-${index % 5}`} type="button" key={item.id} onClick={() => setActiveItem(item)}><img src={item.image_url} srcSet={`${item.image_url} 900w`} sizes="(max-width: 700px) 90vw, 33vw" alt={item.title || item.category || 'تصویر گالری بهارناژ'} loading="lazy" decoding="async" /><span className="gallery-card-overlay"><strong>{item.title || item.category}</strong>{item.category && <small>{item.category}</small>}</span></button>)}</div> : <p className="gallery-state">در این دسته تصویری ثبت نشده است.</p>}</>}{activeItem && <div className="lightbox" role="presentation" onMouseDown={() => setActiveItem(null)}><div className="lightbox-content" role="dialog" aria-modal="true" aria-label={activeItem.title || 'نمایش تصویر'} onMouseDown={(event) => event.stopPropagation()}><button className="lightbox-close" type="button" onClick={() => setActiveItem(null)} aria-label="بستن">×</button><img src={activeItem.image_url} alt={activeItem.title || activeItem.category || 'تصویر گالری'} /><div><strong>{activeItem.title || activeItem.category}</strong>{activeItem.description && <p>{activeItem.description}</p>}</div></div></div>}</section>
}
