import Disclosure from '../components/TelegramDisclosure'
import { useEffect, useRef, useState } from 'react'
import { api } from '../shared/api'
import TelegramConnect from '../components/TelegramConnect'
import PasswordInput from '../components/PasswordInput'

const emptySecrets = { token: '', integration_secret: '' }
const explainError = error => {
  const data = error.response?.data
  return typeof data?.detail === 'string' ? data.detail : data ? Object.values(data).flat().join('؛ ') : 'ارتباط برقرار نشد. دوباره تلاش کنید.'
}
export default function TelegramSetup({ onHelp }) {
  const [saved, setSaved] = useState(null), [form, setForm] = useState(null)
  const [secrets, setSecrets] = useState(emptySecrets), [busy, setBusy] = useState(false), [notice, setNotice] = useState(null)
  const noticeRef=useRef(null)
  useEffect(()=>{if(notice)noticeRef.current?.scrollIntoView?.({block:'nearest'})},[notice])
  const [mode, setMode] = useState('off'), [confirmed, setConfirmed] = useState(false)
  const accept = data => { setSaved(data); setForm({ bot_username: data.bot_username || '', site_url: data.site_url || '', backend_url: data.backend_url || '' }); setMode(data.mode); setConfirmed(false) }
  useEffect(() => { let active=true; api.get('telegram/admin/setup/').then(({ data }) => { if(active) accept(data) }).catch(e => { if(active) setNotice({ error: true, text: explainError(e) }) }); return () => { active=false } }, [])
  const request = async (fn, success) => { setBusy(true); setNotice(null); try { const { data } = await fn(); accept(data); setSecrets(emptySecrets); setNotice({ text: success }) } catch(e) { setNotice({ error: true, text: explainError(e) }) } finally { setBusy(false) } }
  const dirty = !!saved && (!!secrets.token || !!secrets.integration_secret || Object.keys(form).some(key => form[key] !== (saved[key] || '')))
  const save = event => { event.preventDefault(); request(() => api.patch('telegram/admin/setup/', { ...form, ...secrets, revision: saved.revision }), 'اطلاعات ذخیره شد. اگر رمز یا توکن را تغییر داده‌اید، ارسال متوقف شده است؛ اتصال را دوباره بررسی کنید.') }
  const copy = async () => { try { await navigator.clipboard.writeText(secrets.integration_secret); setNotice({ text: 'رمز کپی شد. آن را در تنظیمات خصوصی TeleBotHost قرار دهید.' }) } catch { setNotice({ error: true, text: 'کپی خودکار ممکن نشد. رمز را از کادر انتخاب و کپی کنید.' }) } }
  return <section className="tg-setup"><div className="tg-section-heading"><div><h2>اتصال ربات سالن</h2><p>اطلاعات ربات را یک‌بار وارد کنید. برای کارهای روزانه نیازی به تغییر آن‌ها نیست.</p></div><button onClick={() => onHelp('start')}>راهنمای راه‌اندازی</button></div>
    {notice && <p ref={noticeRef} className={notice.error ? 'tg-notice tg-error' : 'tg-notice'} role={notice.error ? 'alert' : 'status'}>{notice.text}</p>}
    {!saved ? <p role="status">{notice?.error ? 'برای تلاش دوباره، صفحه را تازه کنید.' : 'در حال دریافت تنظیمات…'}</p> : <fieldset disabled={busy} className="tg-unboxed">
      {(!saved.credentials_readable || saved.emergency_stop) && <p className="tg-notice tg-error" role="alert">{saved.emergency_stop ? 'ارسال از تنظیمات سرور متوقف شده است. برای فعال‌سازی با مسئول راه‌اندازی تماس بگیرید.' : 'رمزهای ذخیره‌شده قابل خواندن نیستند. از مسئول راه‌اندازی بخواهید کلید سرور را بررسی کند.'}</p>}
      <form onSubmit={save} autoComplete="off">
        <div className="tg-setup-step"><span className="tg-number">۱</span><div><h3>اطلاعات ربات</h3><p>توکن را از <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">BotFather رسمی</a> بگیرید. توکن را برای مشتریان نفرستید.</p></div></div>
        <div className="telegram-grid"><label>توکن ربات <span className="tg-muted">{saved.token_present ? 'ذخیره شده؛ فقط برای تعویض وارد کنید' : 'هنوز ذخیره نشده'}</span><PasswordInput visibilityLabel="توکن ربات" dir="ltr" autoComplete="new-password" spellCheck={false} maxLength={160} value={secrets.token} onChange={e => setSecrets({ ...secrets, token: e.target.value })} placeholder={saved.token_present ? 'برای نگه داشتن توکن، خالی بگذارید' : 'توکن دریافتی از BotFather'} /></label><label>نام یا پیوند ربات <span className="tg-muted">پس از بررسی توکن، خودکار تکمیل می‌شود</span><input dir="ltr" spellCheck={false} value={form.bot_username} onChange={e => setForm({ ...form, bot_username: e.target.value })} placeholder="https://t.me/YourSalonBot" /></label></div>
        <Disclosure className="tg-disclosure" open={!saved.secret_present || undefined}><summary>اتصال سایت و ربات <span>تنظیم اولیه با کمک مسئول راه‌اندازی</span></summary><div className="tg-disclosure-body"><p>ربات در TeleBotHost پیام مشتری را دریافت می‌کند و سایت، نوبت‌ها و ارسال‌ها را مدیریت می‌کند. هر دو باید همین رمز اتصال را داشته باشند.</p><label>رمز اتصال به TeleBotHost <span className="tg-muted">{saved.secret_present ? 'ذخیره شده؛ خالی یعنی بدون تغییر' : 'با دکمه زیر یک رمز بسازید و قبل از ذخیره کپی کنید'}</span><PasswordInput visibilityLabel="رمز اتصال" dir="ltr" autoComplete="new-password" spellCheck={false} maxLength={200} value={secrets.integration_secret} onChange={e => setSecrets({ ...secrets, integration_secret: e.target.value })} /></label><div className="telegram-actions"><button type="button" onClick={() => { const bytes=crypto.getRandomValues(new Uint8Array(32)); setSecrets({ ...secrets, integration_secret: Array.from(bytes, b => b.toString(16).padStart(2,'0')).join('') }) }}>ساخت رمز اتصال</button><button type="button" disabled={!secrets.integration_secret} onClick={copy}>کپی رمز برای TeleBotHost</button></div><p className="tg-muted">رمز ذخیره‌شده دوباره نمایش داده نمی‌شود. با ساخت رمز تازه، مقدار TeleBotHost هم باید عوض شود.</p><div className="telegram-grid"><label>نشانی اصلی سایت<input type="url" dir="ltr" value={form.site_url} onChange={e => setForm({ ...form, site_url: e.target.value })} placeholder="https://example.com" /></label><label>نشانی اصلی سرور<input type="url" dir="ltr" value={form.backend_url} onChange={e => setForm({ ...form, backend_url: e.target.value })} placeholder="https://api.example.com" /></label></div><details><summary>اطلاعاتی که مسئول راه‌اندازی نیاز دارد</summary><p>در ENV خصوصی TeleBotHost، نشانی سرور بالا را برای <bdi>BAHARNAJ_BACKEND_URL</bdi> و رمز کپی‌شده را برای <bdi>BAHARNAJ_INTEGRATION_SECRET</bdi> وارد کنید. فایل فرمان ربات و اجرای منظم ارسال‌ها هم باید نصب شوند؛ مسئول راه‌اندازی راهنمای پوشه telegram را دنبال کند.</p></details></div></Disclosure>
        <div className="telegram-actions"><button className="tg-primary" type="submit">{busy ? 'در حال انجام…' : 'ذخیره اطلاعات ربات'}</button><button type="button" disabled={!saved.token_present || dirty} onClick={() => request(() => api.post('telegram/admin/setup/', { action: 'verify' }), 'توکن معتبر است و نام ربات تأیید شد. هیچ پیامی ارسال نشد.')}>بررسی توکن</button><span className="tg-muted">{saved.verified_at ? '✓ توکن بررسی شده است' : 'بررسی توکن، پیامی برای کسی نمی‌فرستد.'}</span></div>
      </form>
      <Disclosure className="tg-disclosure"><summary>وضعیت ارسال <span>{({ off: 'متوقف', test: 'آزمایشی؛ بدون پیام واقعی', live: 'ارسال واقعی فعال' })[saved.mode]}</span></summary><div className="tg-disclosure-body"><p>پس از نصب فرمان‌های ربات و اجرای خودکار، وضعیت ارسال را انتخاب کنید. ذخیره توکن به‌تنهایی ارسال را فعال نمی‌کند.</p><label>ارسال پیام از سایت<select value={mode} onChange={e => { setMode(e.target.value); setConfirmed(false) }}><option value="off">متوقف</option><option value="test">آزمایشی — بدون ارسال واقعی</option><option value="live">فعال — ارسال واقعی</option></select></label>{mode === 'live' && saved.mode !== 'live' && <label className="telegram-check"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />می‌دانم پیام‌های آماده برای مشتریان موافق ارسال خواهند شد.</label>}<p className="tg-muted">{saved.worker_recent ? '✓ اجرای خودکار به‌روز است.' : 'اجرای خودکار هنوز تأیید نشده یا به‌روز نیست. مسئول راه‌اندازی باید آن را بررسی کند.'}</p><button className="tg-primary" disabled={dirty || (mode === 'live' && saved.mode !== 'live' && (!confirmed || !saved.verified_at))} onClick={() => request(() => api.patch('telegram/admin/setup/', { mode, confirm_live: confirmed, revision: saved.revision }), 'وضعیت ارسال ذخیره شد.')}>ثبت وضعیت ارسال</button></div></Disclosure>
      <Disclosure className="tg-disclosure"><summary>دریافت پیام آزمایشی در تلگرام خودم <span>اتصال حساب مدیر</span></summary><div className="tg-disclosure-body"><p>ابتدا حالت آزمایشی یا ارسال واقعی را فعال کنید. سپس حساب خودتان را وصل کنید و دریافت گزارش مدیریت را انتخاب کنید. نمونه پیام فقط به حساب مدیر خودتان فرستاده می‌شود.</p><TelegramConnect /></div></Disclosure>
    </fieldset>}
  </section>
}
