# Generated by Django 6.1 on 2026-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0012_customerprofile_profile_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="last_visit",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="no_show_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="tags",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
