# Generated by Django 6.1 on 2026-08-28 12:29

import django.db.models.deletion
import salon.models
import uuid
from django.db import migrations, models


def drop_overlap_triggers(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS salon_appointmentitem_no_overlap_insert")
        schema_editor.execute("DROP TRIGGER IF EXISTS salon_appointmentitem_no_overlap_update")


def restore_overlap_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    schema_editor.execute("""
        CREATE TRIGGER salon_appointmentitem_no_overlap_insert
        BEFORE INSERT ON salon_appointmentitem
        WHEN EXISTS (SELECT 1 FROM salon_appointmentitem AS existing JOIN salon_appointment AS appointment ON appointment.id = existing.appointment_id WHERE existing.employee_id = NEW.employee_id AND existing.date = NEW.date AND appointment.status IN ('pending', 'confirmed') AND NEW.start_time < existing.end_time AND NEW.end_time > existing.start_time)
        BEGIN SELECT RAISE(ABORT, 'employee appointment items overlap'); END;
    """)
    schema_editor.execute("""
        CREATE TRIGGER salon_appointmentitem_no_overlap_update
        BEFORE UPDATE OF employee_id, date, start_time, end_time, appointment_id ON salon_appointmentitem
        WHEN EXISTS (SELECT 1 FROM salon_appointmentitem AS existing JOIN salon_appointment AS appointment ON appointment.id = existing.appointment_id WHERE existing.id != NEW.id AND existing.employee_id = NEW.employee_id AND existing.date = NEW.date AND appointment.status IN ('pending', 'confirmed') AND NEW.start_time < existing.end_time AND NEW.end_time > existing.start_time)
        BEGIN SELECT RAISE(ABORT, 'employee appointment items overlap'); END;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0013_customerprofile_last_visit_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_overlap_triggers, migrations.RunPython.noop),
        migrations.AddField(
            model_name="appointment",
            name="confirmation_code",
            field=models.CharField(
                default=salon.models.generate_confirmation_code,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="BookingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon.employeeprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salon.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=20)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.employeeprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="salon.service"
                    ),
                ),
            ],
        ),
        migrations.RunPython(restore_overlap_triggers, migrations.RunPython.noop),
    ]
