# Generated by Django 6.1 on 2026-08-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0014_appointment_confirmation_code_bookinghold_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryasset",
            options={"ordering": ("display_order", "-created_at")},
        ),
    ]
