# Generated by Django 6.1 on 2026-08-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0015_alter_galleryasset_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghold",
            name="owner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="BookingHoldItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="salon.employeeprofile")),
                ("hold", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="salon.bookinghold")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="salon.service")),
            ],
        ),
    ]