# Generated by Django 6.1 on 2026-09-07 14:40

from django.db import migrations, models
from importlib import import_module

# SQLite rebuilds the table when adding JSON defaults; preserve the existing
# booking-overlap guards on both forward and reverse migration.
_overlap = import_module("salon.migrations.0014_appointment_confirmation_code_bookinghold_and_more")
drop_overlap_triggers = _overlap.drop_overlap_triggers
restore_overlap_triggers = _overlap.restore_overlap_triggers


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0024_blogcategory_blogtag_blogpost_blogmedia_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_overlap_triggers, restore_overlap_triggers),
        migrations.AddField(
            model_name="appointmentitem",
            name="catalog_pricing_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="appointmentitem",
            name="final_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="maximum_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="minimum_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="pricing_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "FIXED"),
                    ("STARTING_FROM", "STARTING_FROM"),
                    ("RANGE", "RANGE"),
                    ("CONSULTATION", "CONSULTATION"),
                    ("VARIABLE", "VARIABLE"),
                ],
                default="FIXED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(restore_overlap_triggers, drop_overlap_triggers),
    ]
