# Generated by Django 6.1 on 2026-09-14 10:27

from django.db import migrations, models
from importlib import import_module

# SQLite schema changes may rebuild the table. Retain the existing overlap guards.
_overlap = import_module("salon.migrations.0014_appointment_confirmation_code_bookinghold_and_more")
drop_overlap_triggers = _overlap.drop_overlap_triggers
restore_overlap_triggers = _overlap.restore_overlap_triggers


def backfill_completed_at(apps, schema_editor):
    # Historical best available audit timestamp; future completions record an explicit instant.
    Item = apps.get_model('salon', 'AppointmentItem')
    Item.objects.filter(completion_status='completed', completed_at=None).update(completed_at=models.F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0025_flexible_service_pricing"),
    ]

    operations = [
        migrations.RunPython(drop_overlap_triggers, restore_overlap_triggers),
        migrations.AddField(
            model_name="appointmentitem",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
        migrations.RunPython(restore_overlap_triggers, drop_overlap_triggers),
    ]
