# Generated by Django 6.1 on 2026-09-09 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from importlib import import_module

_overlap = import_module('salon.migrations.0014_appointment_confirmation_code_bookinghold_and_more')


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0025_flexible_service_pricing"),
    ]

    operations = [
        migrations.RunPython(_overlap.drop_overlap_triggers, _overlap.restore_overlap_triggers),
        migrations.CreateModel(
            name="SMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salon_name", models.CharField(default="بهارناژ", max_length=100)),
                ("booking_link", models.URLField(blank=True)),
                ("manager_phone", models.CharField(blank=True, max_length=20)),
                ("daily_summary_enabled", models.BooleanField(default=False)),
                ("daily_summary_hour", models.PositiveSmallIntegerField(default=21)),
                ("campaign_summary_enabled", models.BooleanField(default=False)),
                ("failure_alert_enabled", models.BooleanField(default=False)),
                ("batch_size", models.PositiveSmallIntegerField(default=50)),
                ("last_worker_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="marketing_opted_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="marketing_sms_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SMSAutomation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("birthday", "birthday"),
                            ("service_reminder", "service_reminder"),
                            ("inactive", "inactive"),
                            ("appointment_reminder", "appointment_reminder"),
                            ('appointment_created', 'appointment_created'),
                            ('appointment_confirmed', 'appointment_confirmed'),
                            ('appointment_changed', 'appointment_changed'),
                            ('appointment_cancelled', 'appointment_cancelled'),
                        ],
                        max_length=30,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("message", models.TextField(max_length=2000)),
                ("interval_days", models.PositiveIntegerField(default=30)),
                ("hours_before", models.PositiveIntegerField(default=24)),
                ("segment", models.JSONField(blank=True, default=dict)),
                ("booking_link", models.URLField(blank=True)),
                ("discount_code", models.CharField(blank=True, max_length=80)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.servicecategory",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("message", models.TextField(max_length=2000)),
                ("segment", models.JSONField(default=dict)),
                ("discount_code", models.CharField(blank=True, max_length=80)),
                ("booking_link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("scheduled", "scheduled"),
                            ("queued", "queued"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("audience_snapshot", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSConsentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed", models.BooleanField()),
                ("evidence", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sms_consent_events",
                        to="salon.customerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("marketing", "marketing"),
                            ("transactional", "transactional"),
                            ("management", "management"),
                            ("test", "test"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("sending", "sending"),
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                            ("unknown", "unknown"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("provider", models.CharField(blank=True, max_length=255)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.appointment",
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="salon.smsautomation",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="salon.smscampaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sms_history",
                        to="salon.customerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SMSAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="sending", max_length=20)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="salon.smsdelivery",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="smsdelivery",
            index=models.Index(fields=["status", "created_at"], name="sms_queue_idx"),
        ),
        migrations.RunPython(_overlap.restore_overlap_triggers, _overlap.drop_overlap_triggers),
    ]
