# Generated by Django 6.1 on 2026-09-14 10:34

from django.db import migrations, models
from importlib import import_module

# SQLite schema changes may rebuild the table. Retain the existing overlap guards.
_overlap = import_module("salon.migrations.0014_appointment_confirmation_code_bookinghold_and_more")
drop_overlap_triggers = _overlap.drop_overlap_triggers
restore_overlap_triggers = _overlap.restore_overlap_triggers


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0026_appointmentitem_completed_at"),
    ]

    operations = [
        migrations.RunPython(drop_overlap_triggers, restore_overlap_triggers),
        migrations.AddField(
            model_name="appointmentitem",
            name="discount_amount",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="appointmentitem",
            name="discount_applied",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(restore_overlap_triggers, drop_overlap_triggers),
    ]
