# Generated by Django 6.1 on 2026-09-21 09:54

import re

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def classify_customer_identities(apps, schema_editor):
    User = apps.get_model("salon", "User")
    groups = {}
    for user in User.objects.filter(role="customer").order_by("pk"):
        phone = re.sub(r"[\s-]", "", user.phone or "")
        if phone.startswith("+98"):
            phone = "0" + phone[3:]
        elif phone.startswith("0098"):
            phone = "0" + phone[4:]
        guest = user.username.startswith(("guest_", "employee_guest_")) or not user.password or user.password.startswith("!")
        normalized_phone = phone if re.fullmatch(r"09\d{9}", phone) else None
        User.objects.filter(pk=user.pk).update(normalized_phone=normalized_phone, is_guest=guest)
        if normalized_phone and user.account_status == "active" and not guest:
            groups.setdefault(phone, []).append(user)
    for phone, users in groups.items():
        if len(users) < 2:
            continue
        canonical = next((user for user in users if user.username == phone), users[0])
        User.objects.filter(pk__in=[user.pk for user in users]).update(identity_conflict=True)
        User.objects.filter(pk__in=[user.pk for user in users if user.pk != canonical.pk]).update(is_guest=True)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("salon", "0030_alter_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerIdentityClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verification_method", models.CharField(default="confirmation_code", max_length=40)),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerLegalAcceptance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("terms_version", models.CharField(max_length=40)),
                ("privacy_version", models.CharField(max_length=40)),
                ("source", models.CharField(choices=[("signup", "Standalone signup"), ("booking", "Booking account creation")], max_length=20)),
                ("accepted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
            ],
            options={"ordering": ("-accepted_at",)},
        ),
        migrations.AlterModelOptions(name="user", options={}),
        migrations.AddField(model_name="customeraccountdeletionrequest", name="cancelled_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="customeraccountdeletionrequest", name="processing_notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="user", name="identity_conflict", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="user", name="is_guest", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="user", name="normalized_phone", field=models.CharField(blank=True, db_index=True, max_length=11, null=True)),
        migrations.AlterField(model_name="customeraccountdeletionrequest", name="status", field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
        migrations.RunPython(classify_customer_identities, migrations.RunPython.noop),
        migrations.AddConstraint(model_name="user", constraint=models.UniqueConstraint(condition=models.Q(("account_status", "active"), ("is_guest", False), ("normalized_phone__isnull", False), ("role", "customer")), fields=("normalized_phone",), name="unique_active_customer_login_phone")),
        migrations.AddField(model_name="customeridentityclaim", name="appointment", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="identity_claims", to="salon.appointment")),
        migrations.AddField(model_name="customeridentityclaim", name="customer", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="identity_claims", to="salon.customerprofile")),
        migrations.AddField(model_name="customeridentityclaim", name="legacy_customer", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claimed_identity_records", to="salon.customerprofile")),
        migrations.AddField(model_name="customerlegalacceptance", name="customer", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="legal_acceptances", to="salon.customerprofile")),
        migrations.AddConstraint(model_name="customeridentityclaim", constraint=models.UniqueConstraint(fields=("customer", "legacy_customer"), name="unique_customer_identity_claim")),
        migrations.AddConstraint(model_name="customerlegalacceptance", constraint=models.UniqueConstraint(fields=("customer", "terms_version", "privacy_version", "source"), name="unique_customer_legal_acceptance")),
    ]
