# Generated by Django 6.1 on 2026-09-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0031_customeridentityclaim_customerlegalacceptance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalonClosure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("kind", models.CharField(choices=[("holiday", "Holiday"), ("maintenance", "Maintenance"), ("private_event", "Private event"), ("other", "Other")], default="holiday", max_length=20)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_salon_closures", to="salon.user")),
                ("updated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="updated_salon_closures", to="salon.user")),
            ],
            options={"ordering": ("start_date",)},
        ),
    ]
