# Generated by Django 6.1 on 2026-09-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("salon", "0032_salonclosure")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(choices=[("appointment_created", "Appointment created"), ("appointment_assigned", "Appointment assigned"), ("appointment_rescheduled", "Appointment rescheduled"), ("appointment_cancelled", "Appointment cancelled"), ("appointment_updated", "Appointment updated"), ("payment_reported", "Payment reported"), ("payment_confirmed", "Payment confirmed"), ("payment_rejected", "Payment rejected"), ("customer_account", "Customer account"), ("leave_reviewed", "Leave reviewed")], max_length=40),
        ),
        migrations.AddField(
            model_name="timeoff",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("withdrawn", "Withdrawn")], default="approved", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(model_name="timeoff", name="review_notes", field=models.CharField(blank=True, max_length=500)),
        migrations.AddField(model_name="timeoff", name="reviewed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(
            model_name="timeoff",
            name="reviewed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_time_off", to="salon.user"),
        ),
        migrations.AlterModelOptions(name="timeoff", options={"ordering": ("-created_at",)}),
        migrations.AlterField(
            model_name="timeoff",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("withdrawn", "Withdrawn")], default="pending", max_length=20),
        ),
    ]
