# Generated by Django 6.1 on 2026-09-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("salon", "0033_timeoff_approval")]

    operations = [
        migrations.AddField(model_name="user", name="totp_enabled", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="user", name="totp_last_used_counter", field=models.BigIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="user", name="totp_pending_created_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="user", name="totp_pending_secret", field=models.TextField(blank=True)),
        migrations.AddField(model_name="user", name="totp_secret", field=models.TextField(blank=True)),
        migrations.CreateModel(
            name="AdminRecoveryCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="admin_recovery_codes", to="salon.user")),
            ],
        ),
        migrations.AddIndex(model_name="adminrecoverycode", index=models.Index(fields=["user", "used_at"], name="admin_recovery_user_used_idx")),
    ]
