# Generated by Django 6.1 on 2026-09-23 22:12

from django.db import migrations, models


def preserve_visible_order(apps, schema_editor):
    Service = apps.get_model("salon", "Service")
    Employee = apps.get_model("salon", "EmployeeProfile")
    database = schema_editor.connection.alias
    current_category = None
    position = 0
    for service in Service._base_manager.using(database).order_by("category_id", "name", "pk"):
        if service.category_id != current_category:
            current_category = service.category_id
            position = 0
        Service._base_manager.using(database).filter(pk=service.pk).update(display_order=position)
        position += 1
    for position, employee in enumerate(Employee._base_manager.using(database).order_by("pk")):
        Employee._base_manager.using(database).filter(pk=employee.pk).update(display_order=position)


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0034_user_totp_and_admin_recovery_codes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={"ordering": ("display_order", "pk")},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": (
                    "category__display_order",
                    "category_id",
                    "display_order",
                    "pk",
                )
            },
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(preserve_visible_order, migrations.RunPython.noop),
    ]
